import type {
  AssessmentKind,
  PublishedCourseVersion,
  ResourceKind,
} from "../../app/domain/catalog";

export type ComputerScienceTopicSpec = {
  readonly key: string;
  readonly title: string;
  readonly assessmentPosition?: "applied" | "final";
};

type EightTopics = readonly [
  ComputerScienceTopicSpec,
  ComputerScienceTopicSpec,
  ComputerScienceTopicSpec,
  ComputerScienceTopicSpec,
  ComputerScienceTopicSpec,
  ComputerScienceTopicSpec,
  ComputerScienceTopicSpec,
  ComputerScienceTopicSpec,
];

export type ComputerScienceCourseSpec = {
  readonly key: string;
  readonly code: string;
  readonly slug: string;
  readonly title: string;
  readonly term: 1 | 2 | 3 | 4 | 5 | 6;
  readonly credits: number;
  readonly format: PublishedCourseVersion["format"];
  readonly summary: string;
  readonly primaryOutcome: string;
  readonly prerequisiteKeys: readonly string[];
  readonly competencyKeys: readonly string[];
  readonly topics: EightTopics;
  readonly assessmentKinds?: readonly [AssessmentKind, AssessmentKind];
  readonly concentrationKey?: "intelligent-systems" | "scalable-secure-systems" | "interactive-applications";
  readonly resource: {
    readonly slug: string;
    readonly title: string;
    readonly provider: string;
    readonly url: string;
    readonly kind: ResourceKind;
    readonly authors: readonly string[];
  };
};

export const computerScienceCourseSpecs = [
  {
    key: "programming-1",
    code: "CS101",
    slug: "programming-1",
    title: "Programming I: Computational Problem Solving",
    term: 1,
    credits: 4,
    format: "studio",
    summary:
      "Python programming, decomposition, testing, debugging, files, regular expressions, and object-oriented design.",
    primaryOutcome:
      "Design, test, document, and defend a program that turns a real problem into reliable software.",
    prerequisiteKeys: [],
    competencyKeys: ["programming", "software"],
    topics: [
      { key: "functions-variables-and-expressions", title: "functions, variables, and expressions" },
      { key: "conditionals-and-boolean-reasoning", title: "conditionals and Boolean reasoning" },
      { key: "loops-invariants-and-iteration", title: "loops, invariants, and iteration" },
      { key: "exceptions-and-systematic-debugging", title: "exceptions and systematic debugging", assessmentPosition: "applied" },
      { key: "libraries-apis-and-dependency-choices", title: "libraries, APIs, and dependency choices" },
      { key: "unit-tests-and-test-design", title: "unit tests and test design" },
      { key: "files-regular-expressions-and-data-validation", title: "files, regular expressions, and data validation" },
      { key: "classes-composition-and-a-final-python-application", title: "classes, composition, and a final Python application", assessmentPosition: "final" },
    ],
    resource: {
      slug: "cs50-introduction-to-programming-with-python",
      title: "CS50’s Introduction to Programming with Python",
      provider: "Harvard University CS50",
      url: "https://cs50.harvard.edu/python/",
      kind: "course",
      authors: ["David J. Malan", "Harvard CS50 staff"],
    },
  },
  {
    key: "discrete-mathematics",
    code: "MATH110",
    slug: "discrete-mathematics-for-computing",
    title: "Discrete Mathematics for Computing",
    term: 1,
    credits: 4,
    format: "theory",
    summary:
      "Proof, sets, relations, graphs, state machines, modular arithmetic, counting, and discrete probability.",
    primaryOutcome:
      "Write sound proofs and apply discrete structures to algorithms, software, and finite systems.",
    prerequisiteKeys: [],
    competencyKeys: ["mathematics", "algorithms"],
    topics: [
      { key: "propositions-predicates-and-proof-structure", title: "propositions, predicates, and proof structure" },
      { key: "sets-functions-relations-and-induction", title: "sets, functions, relations, and induction" },
      { key: "strong-induction-and-recursive-definitions", title: "strong induction and recursive definitions" },
      { key: "graphs-trees-and-graph-invariants", title: "graphs, trees, and graph invariants", assessmentPosition: "applied" },
      { key: "state-machines-and-invariants", title: "state machines and invariants" },
      { key: "number-theory-and-modular-arithmetic", title: "number theory and modular arithmetic" },
      { key: "counting-recurrences-and-asymptotics", title: "counting, recurrences, and asymptotics" },
      { key: "discrete-probability-and-cumulative-proof-practice", title: "discrete probability and cumulative proof practice", assessmentPosition: "final" },
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-mathematics-for-computer-science",
      title: "Mathematics for Computer Science",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/",
      kind: "course",
      authors: ["Albert R. Meyer", "Adam Chlipala"],
    },
  },
  {
    key: "calculus",
    code: "MATH120",
    slug: "calculus-for-computing",
    title: "Calculus for Computing",
    term: 1,
    credits: 4,
    format: "theory",
    summary:
      "Single-variable differentiation, integration, approximation, optimization, differential equations, and series.",
    primaryOutcome:
      "Use calculus to model change, optimize systems, and explain numerical approximations used in computing.",
    prerequisiteKeys: [],
    competencyKeys: ["mathematics"],
    topics: [
      { key: "functions-limits-and-continuity", title: "functions, limits, and continuity" },
      { key: "derivatives-from-definitions-and-rules", title: "derivatives from definitions and rules" },
      { key: "linearization-and-numerical-approximation", title: "linearization and numerical approximation" },
      { key: "optimization-and-related-rates", title: "optimization and related rates", assessmentPosition: "applied" },
      { key: "definite-integrals-and-accumulation", title: "definite integrals and accumulation" },
      { key: "the-fundamental-theorem-and-applications", title: "the fundamental theorem and applications" },
      { key: "integration-methods-and-differential-models", title: "integration methods and differential models" },
      { key: "taylor-series-error-and-cumulative-modeling", title: "Taylor series, error, and cumulative modeling", assessmentPosition: "final" },
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-single-variable-calculus",
      title: "Single Variable Calculus",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/",
      kind: "course",
      authors: ["David Jerison", "MIT Mathematics"],
    },
  },
  {
    key: "systems-foundations",
    code: "CS110",
    slug: "computer-systems-foundations",
    title: "Computer Systems Foundations",
    term: 1,
    credits: 4,
    format: "laboratory",
    summary:
      "C programming, memory, data representation, algorithms, SQL, and the layers connecting source code to machines.",
    primaryOutcome:
      "Explain how programs use memory and implement a tested systems-oriented application in C.",
    prerequisiteKeys: ["programming-1"],
    competencyKeys: ["programming", "systems"],
    topics: [
      { key: "computational-thinking-and-c-toolchains", title: "computational thinking and C toolchains" },
      { key: "c-control-flow-functions-and-compilation", title: "C control flow, functions, and compilation" },
      { key: "arrays-strings-and-data-representation", title: "arrays, strings, and data representation" },
      { key: "algorithmic-costs-and-empirical-measurement", title: "algorithmic costs and empirical measurement", assessmentPosition: "applied" },
      { key: "pointers-memory-layout-and-allocation", title: "pointers, memory layout, and allocation" },
      { key: "linked-structures-and-memory-safety", title: "linked structures and memory safety" },
      { key: "sql-and-durable-data", title: "SQL and durable data" },
      { key: "systems-integration-and-a-cumulative-c-build", title: "systems integration and a cumulative C build", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "cs50-introduction-to-computer-science",
      title: "CS50’s Introduction to Computer Science",
      provider: "Harvard University CS50",
      url: "https://cs50.harvard.edu/x/",
      kind: "course",
      authors: ["David J. Malan", "Harvard CS50 staff"],
    },
  },
  {
    key: "technical-communication",
    code: "PROF110",
    slug: "technical-communication",
    title: "Technical Communication for Computing",
    term: 1,
    credits: 4,
    format: "seminar",
    summary:
      "Audience analysis, clear sentences, document structure, evidence, diagrams, accessibility, and technical review.",
    primaryOutcome:
      "Produce concise technical documentation whose claims, procedures, and design decisions can be checked.",
    prerequisiteKeys: [],
    competencyKeys: ["professional", "software"],
    topics: [
      { key: "audience-purpose-and-scope", title: "audience, purpose, and scope" },
      { key: "terminology-active-voice-and-clear-sentences", title: "terminology, active voice, and clear sentences" },
      { key: "paragraphs-lists-and-information-hierarchy", title: "paragraphs, lists, and information hierarchy" },
      { key: "procedures-examples-and-reproducible-instructions", title: "procedures, examples, and reproducible instructions", assessmentPosition: "applied" },
      { key: "markdown-code-samples-and-document-tooling", title: "Markdown, code samples, and document tooling" },
      { key: "diagrams-tables-captions-and-accessibility", title: "diagrams, tables, captions, and accessibility" },
      { key: "source-evaluation-citation-and-uncertainty", title: "source evaluation, citation, and uncertainty" },
      { key: "peer-review-and-a-polished-technical-guide", title: "peer review and a polished technical guide", assessmentPosition: "final" },
    ],
    assessmentKinds: ["portfolio", "presentation"],
    resource: {
      slug: "google-technical-writing-one",
      title: "Technical Writing One",
      provider: "Google for Developers",
      url: "https://developers.google.com/tech-writing/one",
      kind: "course",
      authors: ["Google Technical Writing team"],
    },
  },
  {
    key: "data-structures",
    code: "CS201",
    slug: "data-structures",
    title: "Data Structures and Abstractions",
    term: 2,
    credits: 4,
    format: "laboratory",
    summary:
      "Abstract data types, lists, trees, hash tables, priority queues, graphs, sorting, and amortized analysis.",
    primaryOutcome:
      "Select, implement, test, and empirically evaluate data structures for a stated workload.",
    prerequisiteKeys: ["programming-1", "discrete-mathematics"],
    competencyKeys: ["programming", "algorithms"],
    topics: [
      { key: "interfaces-abstraction-and-asymptotic-cost", title: "interfaces, abstraction, and asymptotic cost" },
      { key: "arrays-linked-lists-stacks-and-queues", title: "arrays, linked lists, stacks, and queues" },
      { key: "testing-invariants-and-encapsulation", title: "testing, invariants, and encapsulation" },
      { key: "hash-tables-and-collision-strategies", title: "hash tables and collision strategies", assessmentPosition: "applied" },
      { key: "trees-traversals-and-search-trees", title: "trees, traversals, and search trees" },
      { key: "priority-queues-heaps-and-disjoint-sets", title: "priority queues, heaps, and disjoint sets" },
      { key: "graphs-and-graph-representations", title: "graphs and graph representations" },
      { key: "sorting-amortized-analysis-and-a-data-structure-library", title: "sorting, amortized analysis, and a data-structure library", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "exam"],
    resource: {
      slug: "berkeley-cs61b-data-structures",
      title: "CS 61B: Data Structures",
      provider: "University of California, Berkeley EECS",
      url: "https://people.eecs.berkeley.edu/~jrs/61b/",
      kind: "course",
      authors: ["Jonathan Shewchuk"],
    },
  },
  {
    key: "computer-architecture",
    code: "CS210",
    slug: "computer-architecture",
    title: "Computer Architecture: From Logic to Machine",
    term: 2,
    credits: 4,
    format: "laboratory",
    summary:
      "Boolean logic, hardware description, ALUs, memory, instruction sets, assemblers, virtual machines, and operating systems.",
    primaryOutcome:
      "Build and explain a functioning computer stack from logic gates through executable programs.",
    prerequisiteKeys: ["systems-foundations", "discrete-mathematics"],
    competencyKeys: ["systems"],
    topics: [
      { key: "boolean-functions-and-elementary-logic-gates", title: "Boolean functions and elementary logic gates" },
      { key: "adders-alus-and-combinational-chips", title: "adders, ALUs, and combinational chips" },
      { key: "registers-memory-and-sequential-logic", title: "registers, memory, and sequential logic" },
      { key: "machine-language-and-instruction-set-design", title: "machine language and instruction-set design", assessmentPosition: "applied" },
      { key: "cpu-and-computer-integration", title: "CPU and computer integration" },
      { key: "assembler-design-and-implementation", title: "assembler design and implementation" },
      { key: "virtual-machines-parsing-and-code-generation", title: "virtual machines, parsing, and code generation" },
      { key: "operating-system-services-and-full-stack-demonstration", title: "operating-system services and full-stack demonstration", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "presentation"],
    resource: {
      slug: "nand2tetris-course",
      title: "Nand2Tetris Course and Projects",
      provider: "Nand2Tetris",
      url: "https://www.nand2tetris.org/course",
      kind: "course",
      authors: ["Noam Nisan", "Shimon Schocken"],
    },
  },
  {
    key: "linear-algebra",
    code: "MATH210",
    slug: "linear-algebra",
    title: "Linear Algebra for Computer Science",
    term: 2,
    credits: 4,
    format: "theory",
    summary:
      "Linear systems, vector spaces, orthogonality, eigenvalues, decompositions, and computational applications.",
    primaryOutcome:
      "Formulate and solve vector and matrix models while explaining numerical and geometric meaning.",
    prerequisiteKeys: ["calculus"],
    competencyKeys: ["mathematics", "ai-data"],
    topics: [
      { key: "linear-systems-and-elimination", title: "linear systems and elimination" },
      { key: "matrix-operations-inverses-and-factorization", title: "matrix operations, inverses, and factorization" },
      { key: "vector-spaces-subspaces-and-basis", title: "vector spaces, subspaces, and basis" },
      { key: "orthogonality-and-least-squares", title: "orthogonality and least squares", assessmentPosition: "applied" },
      { key: "determinants-and-volume", title: "determinants and volume" },
      { key: "eigenvalues-and-eigenvectors", title: "eigenvalues and eigenvectors" },
      { key: "singular-values-and-low-rank-approximation", title: "singular values and low-rank approximation" },
      { key: "numerical-linear-algebra-in-a-computing-application", title: "numerical linear algebra in a computing application", assessmentPosition: "final" },
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-linear-algebra",
      title: "Linear Algebra",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/",
      kind: "course",
      authors: ["Gilbert Strang"],
    },
  },
  {
    key: "probability",
    code: "STAT210",
    slug: "probability-for-computing",
    title: "Probability for Computing",
    term: 2,
    credits: 4,
    format: "theory",
    summary:
      "Counting, conditional probability, random variables, expectation, common distributions, and simulation.",
    primaryOutcome:
      "Build, calculate, simulate, and critique probabilistic models used in algorithms and data systems.",
    prerequisiteKeys: ["calculus", "discrete-mathematics"],
    competencyKeys: ["mathematics", "ai-data"],
    topics: [
      { key: "counting-and-probability-spaces", title: "counting and probability spaces" },
      { key: "conditional-probability-and-bayes-rule", title: "conditional probability and Bayes' rule" },
      { key: "independence-and-probabilistic-reasoning", title: "independence and probabilistic reasoning" },
      { key: "discrete-random-variables-and-expectation", title: "discrete random variables and expectation", assessmentPosition: "applied" },
      { key: "continuous-distributions-and-transformations", title: "continuous distributions and transformations" },
      { key: "joint-distributions-covariance-and-conditioning", title: "joint distributions, covariance, and conditioning" },
      { key: "law-of-large-numbers-and-central-limit-behavior", title: "law of large numbers and central limit behavior" },
      { key: "simulation-estimation-and-a-cumulative-probability-model", title: "simulation, estimation, and a cumulative probability model", assessmentPosition: "final" },
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "harvard-statistics-110",
      title: "Statistics 110: Probability",
      provider: "Harvard University",
      url: "https://stat110.hsites.harvard.edu/",
      kind: "course",
      authors: ["Joe Blitzstein"],
    },
  },
  {
    key: "web-engineering",
    code: "CS220",
    slug: "web-engineering",
    title: "Web Engineering",
    term: 2,
    credits: 4,
    format: "studio",
    summary:
      "Semantic HTML, CSS, JavaScript, accessibility, HTTP, browser APIs, testing, performance, and deployment.",
    primaryOutcome:
      "Ship an accessible, standards-based web application and justify its architecture and performance.",
    prerequisiteKeys: ["programming-1", "technical-communication"],
    competencyKeys: ["software", "human-centered"],
    topics: [
      { key: "web-standards-semantic-html-and-document-structure", title: "web standards, semantic HTML, and document structure" },
      { key: "css-layout-responsive-design-and-maintainability", title: "CSS layout, responsive design, and maintainability" },
      { key: "javascript-the-dom-and-event-driven-behavior", title: "JavaScript, the DOM, and event-driven behavior" },
      { key: "forms-validation-accessibility-and-inclusive-interaction", title: "forms, validation, accessibility, and inclusive interaction", assessmentPosition: "applied" },
      { key: "http-fetch-apis-and-asynchronous-control-flow", title: "HTTP, fetch, APIs, and asynchronous control flow" },
      { key: "client-state-components-and-architecture", title: "client state, components, and architecture" },
      { key: "testing-security-basics-and-performance", title: "testing, security basics, and performance" },
      { key: "deployment-observability-and-a-production-ready-application", title: "deployment, observability, and a production-ready application", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "mdn-learn-web-development",
      title: "Learn Web Development",
      provider: "MDN Web Docs",
      url: "https://developer.mozilla.org/en-US/docs/Learn_web_development",
      kind: "course",
      authors: ["MDN contributors"],
    },
  },
  {
    key: "algorithms",
    code: "CS301",
    slug: "algorithm-design-and-analysis",
    title: "Algorithm Design and Analysis",
    term: 3,
    credits: 4,
    format: "theory",
    summary:
      "Algorithmic modeling, asymptotic analysis, sorting, graph algorithms, dynamic programming, and complexity tradeoffs.",
    primaryOutcome:
      "Design, prove, implement, and measure algorithms while stating the limits of each approach.",
    prerequisiteKeys: ["data-structures", "discrete-mathematics"],
    competencyKeys: ["algorithms", "mathematics"],
    topics: [
      { key: "computational-models-and-asymptotic-analysis", title: "computational models and asymptotic analysis" },
      { key: "recurrences-divide-and-conquer-and-sorting", title: "recurrences, divide-and-conquer, and sorting" },
      { key: "hashing-and-randomized-algorithms", title: "hashing and randomized algorithms" },
      { key: "binary-search-trees-and-augmentation", title: "binary search trees and augmentation", assessmentPosition: "applied" },
      { key: "breadth-first-and-depth-first-graph-search", title: "breadth-first and depth-first graph search" },
      { key: "shortest-paths-and-weighted-graphs", title: "shortest paths and weighted graphs" },
      { key: "dynamic-programming-and-greedy-design", title: "dynamic programming and greedy design" },
      { key: "complexity-evidence-and-a-cumulative-algorithm-portfolio", title: "complexity evidence and a cumulative algorithm portfolio", assessmentPosition: "final" },
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-introduction-to-algorithms",
      title: "Introduction to Algorithms",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/",
      kind: "course",
      authors: ["Erik Demaine", "Srini Devadas"],
    },
  },
  {
    key: "operating-systems",
    code: "CS310",
    slug: "operating-systems",
    title: "Operating Systems",
    term: 3,
    credits: 4,
    format: "laboratory",
    summary:
      "Processes, scheduling, virtual memory, concurrency, synchronization, storage, file systems, and protection.",
    primaryOutcome:
      "Implement and test core operating-system mechanisms and explain their safety and performance tradeoffs.",
    prerequisiteKeys: ["data-structures", "computer-architecture"],
    competencyKeys: ["systems", "security"],
    topics: [
      { key: "processes-system-calls-and-direct-execution", title: "processes, system calls, and direct execution" },
      { key: "cpu-scheduling-and-measurable-policy-tradeoffs", title: "CPU scheduling and measurable policy tradeoffs" },
      { key: "address-spaces-and-memory-apis", title: "address spaces and memory APIs" },
      { key: "paging-translation-and-virtual-memory", title: "paging, translation, and virtual memory", assessmentPosition: "applied" },
      { key: "threads-locks-condition-variables-and-semaphores", title: "threads, locks, condition variables, and semaphores" },
      { key: "concurrency-bugs-and-event-driven-systems", title: "concurrency bugs and event-driven systems" },
      { key: "storage-devices-files-and-file-system-implementation", title: "storage devices, files, and file-system implementation" },
      { key: "persistence-integrity-protection-and-a-systems-lab", title: "persistence, integrity, protection, and a systems lab", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "operating-systems-three-easy-pieces",
      title: "Operating Systems: Three Easy Pieces",
      provider: "University of Wisconsin–Madison authors",
      url: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
      kind: "textbook",
      authors: ["Remzi H. Arpaci-Dusseau", "Andrea C. Arpaci-Dusseau"],
    },
  },
  {
    key: "database-systems",
    code: "CS320",
    slug: "database-systems",
    title: "Database Systems",
    term: 3,
    credits: 4,
    format: "laboratory",
    summary:
      "Relational modeling, SQL, storage, indexes, query execution, transactions, concurrency control, and recovery.",
    primaryOutcome:
      "Design a sound relational system and implement selected database internals with measured behavior.",
    prerequisiteKeys: ["data-structures", "systems-foundations"],
    competencyKeys: ["data", "systems"],
    topics: [
      { key: "data-models-relational-algebra-and-sql", title: "data models, relational algebra, and SQL" },
      { key: "schema-design-dependencies-and-normalization", title: "schema design, dependencies, and normalization" },
      { key: "storage-models-pages-and-buffer-pools", title: "storage models, pages, and buffer pools" },
      { key: "indexes-trees-hashing-and-filters", title: "indexes, trees, hashing, and filters", assessmentPosition: "applied" },
      { key: "query-execution-joins-sorting-and-aggregation", title: "query execution, joins, sorting, and aggregation" },
      { key: "query-planning-and-optimization", title: "query planning and optimization" },
      { key: "transactions-and-concurrency-control", title: "transactions and concurrency control" },
      { key: "logging-recovery-and-a-database-implementation-review", title: "logging, recovery, and a database implementation review", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "cmu-intro-to-database-systems",
      title: "15-445/645: Intro to Database Systems",
      provider: "Carnegie Mellon University Database Group",
      url: "https://15445.courses.cs.cmu.edu/spring2026/",
      kind: "course",
      authors: ["Andy Pavlo", "Jignesh Patel", "CMU Database Group"],
    },
  },
  {
    key: "software-engineering",
    code: "CS330",
    slug: "software-engineering",
    title: "Software Engineering",
    term: 3,
    credits: 4,
    format: "studio",
    summary:
      "Sustainable design, testing, review, dependency management, APIs, build systems, teamwork, and maintenance.",
    primaryOutcome:
      "Evolve a team software system using explicit requirements, tests, review, documentation, and maintenance evidence.",
    prerequisiteKeys: ["data-structures", "web-engineering"],
    competencyKeys: ["software", "professional"],
    topics: [
      { key: "software-engineering-over-time-and-scale", title: "software engineering over time and scale" },
      { key: "team-culture-knowledge-sharing-and-ownership", title: "team culture, knowledge sharing, and ownership" },
      { key: "style-readability-and-documentation", title: "style, readability, and documentation" },
      { key: "testing-strategy-and-test-maintainability", title: "testing strategy and test maintainability", assessmentPosition: "applied" },
      { key: "dependency-management-apis-and-compatibility", title: "dependency management, APIs, and compatibility" },
      { key: "version-control-code-review-and-change-management", title: "version control, code review, and change management" },
      { key: "build-systems-continuous-integration-and-release", title: "build systems, continuous integration, and release" },
      { key: "technical-debt-sustainability-and-a-maintained-team-system", title: "technical debt, sustainability, and a maintained team system", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "software-engineering-at-google",
      title: "Software Engineering at Google",
      provider: "Google / Abseil",
      url: "https://abseil.io/resources/swe-book",
      kind: "textbook",
      authors: ["Titus Winters", "Tom Manshreck", "Hyrum Wright"],
    },
  },
  {
    key: "computer-networks",
    code: "CS340",
    slug: "computer-networks",
    title: "Computer Networks",
    term: 3,
    credits: 4,
    format: "laboratory",
    summary:
      "Layering, packet switching, reliable transport, routing, naming, congestion, network programming, and measurement.",
    primaryOutcome:
      "Implement a reliable transport component and diagnose network behavior from packet-level evidence.",
    prerequisiteKeys: ["systems-foundations", "data-structures"],
    competencyKeys: ["networks", "systems"],
    topics: [
      { key: "network-architecture-layering-and-packet-switching", title: "network architecture, layering, and packet switching" },
      { key: "application-protocols-naming-and-http", title: "application protocols, naming, and HTTP" },
      { key: "sockets-streams-and-network-programming", title: "sockets, streams, and network programming" },
      { key: "reliable-byte-streams-and-retransmission", title: "reliable byte streams and retransmission", assessmentPosition: "applied" },
      { key: "ip-forwarding-addressing-and-routing", title: "IP, forwarding, addressing, and routing" },
      { key: "congestion-control-and-shared-capacity", title: "congestion control and shared capacity" },
      { key: "link-layers-local-networks-and-measurement", title: "link layers, local networks, and measurement" },
      { key: "network-security-operations-and-a-transport-implementation", title: "network security, operations, and a transport implementation", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "stanford-cs144-networking",
      title: "CS 144: Introduction to Computer Networking",
      provider: "Stanford University",
      url: "https://cs144.github.io/",
      kind: "course",
      authors: ["Keith Winstein", "Stanford CS144 staff"],
    },
  },
  {
    key: "theory-of-computation",
    code: "CS401",
    slug: "theory-of-computation",
    title: "Theory of Computation",
    term: 4,
    credits: 4,
    format: "theory",
    summary:
      "Automata, regular and context-free languages, computability, reductions, complexity, and NP-completeness.",
    primaryOutcome:
      "Prove what computational models can and cannot decide and classify the complexity of representative problems.",
    prerequisiteKeys: ["algorithms", "discrete-mathematics"],
    competencyKeys: ["theory", "mathematics"],
    topics: [
      { key: "finite-automata-and-regular-languages", title: "finite automata and regular languages" },
      { key: "regular-expressions-closure-and-pumping-arguments", title: "regular expressions, closure, and pumping arguments" },
      { key: "context-free-grammars-and-pushdown-automata", title: "context-free grammars and pushdown automata" },
      { key: "turing-machines-and-recognizable-languages", title: "Turing machines and recognizable languages", assessmentPosition: "applied" },
      { key: "decidability-and-undecidability", title: "decidability and undecidability" },
      { key: "mapping-reductions-and-proof-technique", title: "mapping reductions and proof technique" },
      { key: "time-complexity-p-and-np", title: "time complexity, P, and NP" },
      { key: "np-completeness-and-cumulative-theory-proofs", title: "NP-completeness and cumulative theory proofs", assessmentPosition: "final" },
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-automata-computability-complexity",
      title: "Automata, Computability, and Complexity",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/6-045j-automata-computability-and-complexity-spring-2011/",
      kind: "course",
      authors: ["Scott Aaronson"],
    },
  },
  {
    key: "programming-languages",
    code: "CS410",
    slug: "programming-languages",
    title: "Programming Languages",
    term: 4,
    credits: 4,
    format: "laboratory",
    summary:
      "Syntax, interpreters, scope, functions, state, types, objects, memory, and language-level tradeoffs.",
    primaryOutcome:
      "Implement interpreters and type checkers while comparing language semantics through executable evidence.",
    prerequisiteKeys: ["data-structures", "discrete-mathematics"],
    competencyKeys: ["programming", "theory"],
    topics: [
      { key: "syntax-abstract-syntax-trees-and-evaluation", title: "syntax, abstract syntax trees, and evaluation" },
      { key: "substitution-environments-and-scope", title: "substitution, environments, and scope" },
      { key: "functions-closures-and-recursion", title: "functions, closures, and recursion" },
      { key: "state-mutation-and-stores", title: "state, mutation, and stores", assessmentPosition: "applied" },
      { key: "data-abstraction-and-object-models", title: "data abstraction and object models" },
      { key: "static-types-type-checking-and-inference", title: "static types, type checking, and inference" },
      { key: "memory-management-and-language-implementation", title: "memory management and language implementation" },
      { key: "language-design-comparison-and-an-interpreter-portfolio", title: "language design comparison and an interpreter portfolio", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "oral"],
    resource: {
      slug: "programming-languages-application-interpretation",
      title: "Programming Languages: Application and Interpretation",
      provider: "Brown University PLT",
      url: "https://www.plai.org/",
      kind: "textbook",
      authors: ["Shriram Krishnamurthi"],
    },
  },
  {
    key: "compilers",
    code: "CS420",
    slug: "compilers-and-language-implementation",
    title: "Compilers and Language Implementation",
    term: 4,
    credits: 4,
    format: "laboratory",
    summary:
      "Scanning, parsing, syntax trees, semantic analysis, bytecode, virtual machines, closures, garbage collection, and optimization.",
    primaryOutcome:
      "Build, test, profile, and explain an interpreter and bytecode virtual machine for a small language.",
    prerequisiteKeys: ["programming-languages", "theory-of-computation"],
    competencyKeys: ["programming", "systems", "theory"],
    topics: [
      { key: "language-design-tokens-and-scanning", title: "language design, tokens, and scanning" },
      { key: "recursive-descent-parsing-and-syntax-trees", title: "recursive-descent parsing and syntax trees" },
      { key: "expression-evaluation-and-runtime-errors", title: "expression evaluation and runtime errors" },
      { key: "statements-control-flow-functions-and-closures", title: "statements, control flow, functions, and closures", assessmentPosition: "applied" },
      { key: "name-resolution-classes-and-inheritance", title: "name resolution, classes, and inheritance" },
      { key: "bytecode-representation-and-virtual-machine-execution", title: "bytecode representation and virtual-machine execution" },
      { key: "values-memory-hash-tables-and-garbage-collection", title: "values, memory, hash tables, and garbage collection" },
      { key: "optimization-diagnostics-and-a-complete-language-implementation", title: "optimization, diagnostics, and a complete language implementation", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "crafting-interpreters",
      title: "Crafting Interpreters",
      provider: "Robert Nystrom",
      url: "https://craftinginterpreters.com/",
      kind: "textbook",
      authors: ["Robert Nystrom"],
    },
  },
  {
    key: "computer-security",
    code: "CS430",
    slug: "computer-security",
    title: "Computer Security",
    term: 4,
    credits: 4,
    format: "laboratory",
    summary:
      "Threat modeling, authentication, access control, web vulnerabilities, secure coding, testing, and incident analysis.",
    primaryOutcome:
      "Find, explain, safely reproduce, and remediate vulnerabilities in an isolated legal training environment.",
    prerequisiteKeys: ["operating-systems", "computer-networks", "web-engineering"],
    competencyKeys: ["security", "systems"],
    topics: [
      { key: "security-goals-threat-models-and-attack-surfaces", title: "security goals, threat models, and attack surfaces" },
      { key: "authentication-sessions-and-access-control", title: "authentication, sessions, and access control" },
      { key: "injection-and-server-side-input-handling", title: "injection and server-side input handling" },
      { key: "cross-site-scripting-and-browser-trust-boundaries", title: "cross-site scripting and browser trust boundaries", assessmentPosition: "applied" },
      { key: "request-forgery-cross-origin-policy-and-clickjacking", title: "request forgery, cross-origin policy, and clickjacking" },
      { key: "file-path-command-and-server-side-request-vulnerabilities", title: "file, path, command, and server-side request vulnerabilities" },
      { key: "business-logic-race-conditions-and-api-security", title: "business logic, race conditions, and API security" },
      { key: "testing-methodology-remediation-and-an-ethical-security-report", title: "testing methodology, remediation, and an ethical security report", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "oral"],
    resource: {
      slug: "portswigger-web-security-academy",
      title: "Web Security Academy",
      provider: "PortSwigger",
      url: "https://portswigger.net/web-security",
      kind: "course",
      authors: ["PortSwigger Web Security Academy"],
    },
  },
  {
    key: "human-computer-interaction",
    code: "CS440",
    slug: "human-computer-interaction",
    title: "Human–Computer Interaction",
    term: 4,
    credits: 4,
    format: "studio",
    summary:
      "Human-centered research, task analysis, ideation, prototyping, usability testing, accessibility, and iterative design.",
    primaryOutcome:
      "Research, prototype, test, and revise an interactive system with traceable evidence from real participants.",
    prerequisiteKeys: ["web-engineering", "technical-communication"],
    competencyKeys: ["human-centered", "professional"],
    topics: [
      { key: "human-centered-design-and-ethical-research", title: "human-centered design and ethical research" },
      { key: "interviews-observation-and-task-analysis", title: "interviews, observation, and task analysis" },
      { key: "personas-scenarios-requirements-and-design-goals", title: "personas, scenarios, requirements, and design goals" },
      { key: "sketching-storyboards-and-design-alternatives", title: "sketching, storyboards, and design alternatives", assessmentPosition: "applied" },
      { key: "low-fidelity-prototypes-and-heuristic-evaluation", title: "low-fidelity prototypes and heuristic evaluation" },
      { key: "interactive-prototypes-and-accessibility", title: "interactive prototypes and accessibility" },
      { key: "usability-studies-measures-and-analysis", title: "usability studies, measures, and analysis" },
      { key: "iteration-design-rationale-and-a-tested-product-prototype", title: "iteration, design rationale, and a tested product prototype", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "uw-cse440-introduction-to-hci",
      title: "CSE 440: Introduction to HCI",
      provider: "University of Washington",
      url: "https://courses.cs.washington.edu/courses/cse440/24au/",
      kind: "course",
      authors: ["University of Washington CSE 440 staff"],
    },
  },
  {
    key: "artificial-intelligence",
    code: "CS501",
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    term: 5,
    credits: 4,
    format: "laboratory",
    summary:
      "Search, adversarial reasoning, constraint satisfaction, probability, decision processes, inference, and learning.",
    primaryOutcome:
      "Implement and compare intelligent-agent techniques while stating assumptions, failure modes, and ethical limits.",
    prerequisiteKeys: ["algorithms", "probability"],
    competencyKeys: ["ai-data", "algorithms"],
    topics: [
      { key: "agents-state-spaces-and-uninformed-search", title: "agents, state spaces, and uninformed search" },
      { key: "heuristics-a-star-and-search-quality", title: "heuristics, A-star, and search quality" },
      { key: "games-minimax-and-adversarial-search", title: "games, minimax, and adversarial search" },
      { key: "constraint-satisfaction-problems", title: "constraint-satisfaction problems", assessmentPosition: "applied" },
      { key: "probability-bayes-nets-and-inference", title: "probability, Bayes nets, and inference" },
      { key: "markov-models-and-decision-processes", title: "Markov models and decision processes" },
      { key: "reinforcement-learning-and-value-estimation", title: "reinforcement learning and value estimation" },
      { key: "machine-learning-overview-and-an-intelligent-agent-project", title: "machine-learning overview and an intelligent-agent project", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "exam"],
    resource: {
      slug: "berkeley-cs188-textbook",
      title: "Introduction to Artificial Intelligence",
      provider: "University of California, Berkeley CS188",
      url: "https://inst.eecs.berkeley.edu/~cs188/textbook/",
      kind: "textbook",
      authors: ["Berkeley CS188 course staff"],
    },
  },
  {
    key: "machine-learning",
    code: "CS510",
    slug: "machine-learning",
    title: "Machine Learning",
    term: 5,
    credits: 4,
    format: "laboratory",
    summary:
      "Regression, classification, data preparation, generalization, neural networks, embeddings, fairness, and production systems.",
    primaryOutcome:
      "Build and evaluate a reproducible machine-learning pipeline with honest metrics and model limitations.",
    prerequisiteKeys: ["linear-algebra", "probability", "programming-1"],
    competencyKeys: ["ai-data", "mathematics", "professional"],
    topics: [
      { key: "problem-framing-data-splits-and-baselines", title: "problem framing, data splits, and baselines" },
      { key: "linear-regression-loss-and-gradient-descent", title: "linear regression, loss, and gradient descent" },
      { key: "logistic-regression-classification-and-metrics", title: "logistic regression, classification, and metrics" },
      { key: "numerical-and-categorical-feature-engineering", title: "numerical and categorical feature engineering", assessmentPosition: "applied" },
      { key: "generalization-overfitting-and-regularization", title: "generalization, overfitting, and regularization" },
      { key: "neural-networks-and-representation-learning", title: "neural networks and representation learning" },
      { key: "production-ml-systems-and-monitoring", title: "production ML systems and monitoring" },
      { key: "fairness-error-analysis-and-a-reproducible-model-card", title: "fairness, error analysis, and a reproducible model card", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "oral"],
    resource: {
      slug: "google-machine-learning-crash-course",
      title: "Machine Learning Crash Course",
      provider: "Google for Developers",
      url: "https://developers.google.com/machine-learning/crash-course",
      kind: "course",
      authors: ["Google Machine Learning Education"],
    },
  },
  {
    key: "distributed-systems",
    code: "CS520",
    slug: "distributed-systems",
    title: "Distributed Systems",
    term: 5,
    credits: 4,
    format: "laboratory",
    summary:
      "Remote communication, failure, consensus, replication, consistency, transactions, distributed storage, and observability.",
    primaryOutcome:
      "Implement and test replicated services under delay, concurrency, restart, and partial failure.",
    prerequisiteKeys: ["operating-systems", "computer-networks", "database-systems"],
    competencyKeys: ["networks", "systems", "data"],
    topics: [
      { key: "distributed-system-models-and-remote-procedure-calls", title: "distributed-system models and remote procedure calls" },
      { key: "time-ordering-concurrency-and-failure", title: "time, ordering, concurrency, and failure" },
      { key: "primary-backup-replication-and-state-machines", title: "primary-backup replication and state machines" },
      { key: "consensus-and-the-raft-protocol", title: "consensus and the Raft protocol", assessmentPosition: "applied" },
      { key: "fault-tolerant-key-value-services", title: "fault-tolerant key-value services" },
      { key: "sharding-reconfiguration-and-transactions", title: "sharding, reconfiguration, and transactions" },
      { key: "consistency-models-and-distributed-storage", title: "consistency models and distributed storage" },
      { key: "measurement-testing-under-failure-and-a-replicated-service", title: "measurement, testing under failure, and a replicated service", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "oral"],
    resource: {
      slug: "mit-distributed-systems",
      title: "6.5840: Distributed Systems",
      provider: "MIT PDOS / CSAIL",
      url: "https://pdos.csail.mit.edu/6.824/",
      kind: "course",
      authors: ["MIT PDOS faculty and course staff"],
    },
  },
  {
    key: "computing-ethics",
    code: "CS530",
    slug: "ethics-of-computing-and-ai",
    title: "Ethics of Computing and AI",
    term: 5,
    credits: 4,
    format: "seminar",
    summary:
      "Ethical reasoning, accountability, transparency, rights, fairness, professional responsibility, and sociotechnical analysis.",
    primaryOutcome:
      "Analyze a computing intervention using evidence, stakeholders, ethical frameworks, and actionable safeguards.",
    prerequisiteKeys: ["technical-communication"],
    competencyKeys: ["ethics", "professional"],
    topics: [
      { key: "sociotechnical-systems-and-ethical-argument", title: "sociotechnical systems and ethical argument" },
      { key: "benefit-harm-non-maleficence-and-uncertainty", title: "benefit, harm, non-maleficence, and uncertainty" },
      { key: "responsibility-accountability-and-governance", title: "responsibility, accountability, and governance" },
      { key: "transparency-explanation-and-contestability", title: "transparency, explanation, and contestability", assessmentPosition: "applied" },
      { key: "privacy-autonomy-and-human-rights", title: "privacy, autonomy, and human rights" },
      { key: "fairness-discrimination-and-measurement", title: "fairness, discrimination, and measurement" },
      { key: "professional-duties-and-responsible-development", title: "professional duties and responsible development" },
      { key: "case-synthesis-safeguards-and-a-public-ethics-review", title: "case synthesis, safeguards, and a public ethics review", assessmentPosition: "final" },
    ],
    assessmentKinds: ["portfolio", "oral"],
    resource: {
      slug: "university-helsinki-ethics-of-ai",
      title: "Ethics of AI",
      provider: "University of Helsinki / MOOC.fi",
      url: "https://ethics-of-ai.mooc.fi/",
      kind: "course",
      authors: ["University of Helsinki Ethics of AI team"],
    },
  },
  {
    key: "capstone-1",
    code: "CS540",
    slug: "capstone-studio-1",
    title: "Capstone Studio I: Proposal and Prototype",
    term: 5,
    credits: 4,
    format: "capstone",
    summary:
      "Problem discovery, project scoping, engineering tools, architecture, risk, research, prototyping, and proposal defense.",
    primaryOutcome:
      "Define a consequential computing problem and defend a feasible, ethical, tested capstone plan and prototype.",
    prerequisiteKeys: ["software-engineering", "algorithms", "human-computer-interaction"],
    competencyKeys: ["capstone", "software", "professional"],
    topics: [
      { key: "problem-discovery-stakeholders-and-evidence", title: "problem discovery, stakeholders, and evidence" },
      { key: "scope-success-criteria-constraints-and-non-goals", title: "scope, success criteria, constraints, and non-goals" },
      { key: "command-line-and-development-environment-reproducibility", title: "command-line and development-environment reproducibility" },
      { key: "version-control-collaboration-and-project-planning", title: "version control, collaboration, and project planning", assessmentPosition: "applied" },
      { key: "architecture-options-and-risk-spikes", title: "architecture options and risk spikes" },
      { key: "debugging-profiling-and-prototype-measurement", title: "debugging, profiling, and prototype measurement" },
      { key: "security-ethics-accessibility-and-failure-planning", title: "security, ethics, accessibility, and failure planning" },
      { key: "proposal-prototype-schedule-and-oral-defense", title: "proposal, prototype, schedule, and oral defense", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "mit-missing-semester",
      title: "The Missing Semester of Your CS Education",
      provider: "MIT",
      url: "https://missing.csail.mit.edu/",
      kind: "course",
      authors: ["MIT Missing Semester instructors"],
    },
  },
  {
    key: "data-science",
    code: "CS601",
    slug: "data-science",
    title: "Data Science and Statistical Inference",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Data tables, visualization, sampling, estimation, hypothesis testing, prediction, uncertainty, and reproducibility.",
    primaryOutcome:
      "Conduct and communicate a reproducible data investigation without overstating what the evidence supports.",
    prerequisiteKeys: ["database-systems", "machine-learning", "probability"],
    competencyKeys: ["ai-data", "data", "professional"],
    topics: [
      { key: "data-generating-processes-tables-and-reproducibility", title: "data-generating processes, tables, and reproducibility" },
      { key: "cleaning-transformation-and-exploratory-visualization", title: "cleaning, transformation, and exploratory visualization" },
      { key: "sampling-empirical-distributions-and-simulation", title: "sampling, empirical distributions, and simulation" },
      { key: "estimation-confidence-intervals-and-uncertainty", title: "estimation, confidence intervals, and uncertainty", assessmentPosition: "applied" },
      { key: "hypothesis-testing-and-error", title: "hypothesis testing and error" },
      { key: "association-correlation-and-linear-prediction", title: "association, correlation, and linear prediction" },
      { key: "classification-evaluation-and-fairness", title: "classification, evaluation, and fairness" },
      { key: "end-to-end-investigation-and-an-evidence-aware-report", title: "end-to-end investigation and an evidence-aware report", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "computational-and-inferential-thinking",
      title: "Computational and Inferential Thinking",
      provider: "UC Berkeley Data 8",
      url: "https://inferentialthinking.com/",
      kind: "textbook",
      authors: ["Ani Adhikari", "John DeNero", "David Wagner"],
    },
  },
  {
    key: "research-methods",
    code: "CS610",
    slug: "computer-science-research-methods",
    title: "Computer Science Research Methods",
    term: 6,
    credits: 4,
    format: "seminar",
    summary:
      "Research questions, paper reading, literature search, method choice, validity, reproducibility, peer review, and proposals.",
    primaryOutcome:
      "Formulate a tractable research question and produce a critical literature review and reproducible study plan.",
    prerequisiteKeys: ["probability", "technical-communication", "algorithms"],
    competencyKeys: ["research", "professional", "mathematics"],
    topics: [
      { key: "research-questions-claims-contribution-types-and-paper-reading", title: "research questions, claims, contribution types, and paper reading" },
      { key: "potential-outcomes-counterfactuals-and-estimands", title: "potential outcomes, counterfactuals, and estimands" },
      { key: "randomized-experiments-power-and-common-validity-threats", title: "randomized experiments, power, and common validity threats" },
      { key: "causal-diagrams-confounding-and-identification-assumptions", title: "causal diagrams, confounding, and identification assumptions", assessmentPosition: "applied" },
      { key: "regression-diagnostics-and-responsible-interpretation", title: "regression, diagnostics, and responsible interpretation" },
      { key: "benchmarks-as-measurement-instruments", title: "benchmarks as measurement instruments" },
      { key: "quasi-experiments-reproducibility-and-research-ethics", title: "quasi-experiments, reproducibility, and research ethics" },
      { key: "literature-synthesis-analysis-plans-and-a-defensible-proposal", title: "literature synthesis, analysis plans, and a defensible proposal", assessmentPosition: "final" },
    ],
    assessmentKinds: ["portfolio", "oral"],
    resource: {
      slug: "princeton-empirical-research-methods-cs",
      title: "COS 598D: Empirical Research Methods for CS",
      provider: "Princeton University",
      url: "https://humans.cs.princeton.edu/teaching/spring2026_empirical_methods.html",
      kind: "course",
      authors: ["Manoel Horta Ribeiro", "Princeton COS 598D course staff"],
    },
  },
  {
    key: "capstone-2",
    code: "CS620",
    slug: "capstone-studio-2",
    title: "Capstone Studio II: Build, Evaluate, and Defend",
    term: 6,
    credits: 4,
    format: "capstone",
    summary:
      "Iterative implementation, review, testing, evaluation, documentation, release, portfolio evidence, and public defense.",
    primaryOutcome:
      "Ship, evaluate, document, and publicly defend a substantial computing artifact and its limitations.",
    prerequisiteKeys: ["capstone-1", "research-methods"],
    competencyKeys: ["capstone", "software", "research", "professional"],
    topics: [
      { key: "reconfirming-requirements-risks-and-evaluation-plan", title: "reconfirming requirements, risks, and evaluation plan" },
      { key: "vertical-slice-implementation-and-continuous-integration", title: "vertical-slice implementation and continuous integration" },
      { key: "design-review-and-evidence-driven-reprioritization", title: "design review and evidence-driven reprioritization" },
      { key: "testing-security-review-and-accessibility-review", title: "testing, security review, and accessibility review", assessmentPosition: "applied" },
      { key: "performance-reliability-and-failure-testing", title: "performance, reliability, and failure testing" },
      { key: "user-or-system-evaluation-and-analysis", title: "user or system evaluation and analysis" },
      { key: "documentation-release-reproducibility-and-handoff", title: "documentation, release, reproducibility, and handoff" },
      { key: "final-artifact-portfolio-retrospective-and-public-defense", title: "final artifact, portfolio, retrospective, and public defense", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "google-engineering-practices-code-review",
      title: "Google Engineering Practices: Code Review",
      provider: "Google",
      url: "https://google.github.io/eng-practices/review/",
      kind: "documentation",
      authors: ["Google Engineering Practices team"],
    },
  },
  {
    key: "computer-graphics",
    code: "CS631",
    slug: "computer-graphics",
    title: "Computer Graphics",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Rasterization, sampling, transforms, meshes, geometry, ray tracing, materials, animation, and simulation.",
    primaryOutcome:
      "Implement a small rendering pipeline and explain visual quality, numerical, and performance tradeoffs.",
    prerequisiteKeys: ["algorithms", "linear-algebra"],
    competencyKeys: ["graphics", "programming", "mathematics"],
    topics: [
      { key: "images-as-data-rasterization-and-sampling", title: "images as data, rasterization, and sampling" },
      { key: "transforms-coordinate-systems-and-texture-mapping", title: "transforms, coordinate systems, and texture mapping" },
      { key: "geometry-processing-and-half-edge-meshes", title: "geometry processing and half-edge meshes" },
      { key: "curves-surfaces-and-mesh-editing", title: "curves, surfaces, and mesh editing", assessmentPosition: "applied" },
      { key: "ray-generation-intersections-and-acceleration", title: "ray generation, intersections, and acceleration" },
      { key: "lighting-materials-and-global-illumination", title: "lighting, materials, and global illumination" },
      { key: "animation-numerical-integration-and-simulation", title: "animation, numerical integration, and simulation" },
      { key: "rendering-system-evaluation-and-a-graphics-project", title: "rendering-system evaluation and a graphics project", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    concentrationKey: "interactive-applications",
    resource: {
      slug: "berkeley-cs184-computer-graphics",
      title: "CS 184/284A: Computer Graphics",
      provider: "University of California, Berkeley",
      url: "https://cs184.eecs.berkeley.edu/sp25/",
      kind: "course",
      authors: ["Ren Ng", "Berkeley CS184 staff"],
    },
  },
  {
    key: "computer-vision",
    code: "CS632",
    slug: "computer-vision",
    title: "Deep Learning for Computer Vision",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Image classification, convolutional networks, optimization, recognition, detection, interpretation, and responsible evaluation.",
    primaryOutcome:
      "Train, diagnose, and communicate a computer-vision system with reproducible evidence and error analysis.",
    prerequisiteKeys: ["machine-learning", "linear-algebra"],
    competencyKeys: ["ai-data", "graphics"],
    topics: [
      { key: "image-classification-and-data-driven-recognition", title: "image classification and data-driven recognition" },
      { key: "linear-classifiers-loss-functions-and-optimization", title: "linear classifiers, loss functions, and optimization" },
      { key: "neural-networks-and-backpropagation", title: "neural networks and backpropagation" },
      { key: "convolutional-architectures-and-training", title: "convolutional architectures and training", assessmentPosition: "applied" },
      { key: "regularization-transfer-learning-and-augmentation", title: "regularization, transfer learning, and augmentation" },
      { key: "detection-segmentation-and-localization", title: "detection, segmentation, and localization" },
      { key: "visualization-interpretation-bias-and-robustness", title: "visualization, interpretation, bias, and robustness" },
      { key: "reproducible-vision-experiment-and-model-report", title: "reproducible vision experiment and model report", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "oral"],
    concentrationKey: "intelligent-systems",
    resource: {
      slug: "stanford-cs231n",
      title: "CS231n: Deep Learning for Computer Vision",
      provider: "Stanford University",
      url: "https://cs231n.stanford.edu/",
      kind: "course",
      authors: ["Stanford CS231n instructors and staff"],
    },
  },
  {
    key: "natural-language-processing",
    code: "CS633",
    slug: "natural-language-processing",
    title: "Natural Language Processing with Deep Learning",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Word vectors, sequence models, attention, transformers, language models, evaluation, bias, and deployment.",
    primaryOutcome:
      "Build and evaluate an NLP model while documenting data, linguistic, ethical, and deployment limitations.",
    prerequisiteKeys: ["machine-learning", "probability"],
    competencyKeys: ["ai-data", "professional"],
    topics: [
      { key: "language-structure-tokenization-and-distributional-meaning", title: "language structure, tokenization, and distributional meaning" },
      { key: "word-vectors-and-representation-geometry", title: "word vectors and representation geometry" },
      { key: "neural-sequence-models-and-recurrent-networks", title: "neural sequence models and recurrent networks" },
      { key: "attention-and-encoder-decoder-models", title: "attention and encoder-decoder models", assessmentPosition: "applied" },
      { key: "transformers-and-pretrained-language-models", title: "transformers and pretrained language models" },
      { key: "question-answering-generation-and-retrieval", title: "question answering, generation, and retrieval" },
      { key: "evaluation-hallucination-bias-and-safety", title: "evaluation, hallucination, bias, and safety" },
      { key: "reproducible-nlp-system-and-model-documentation", title: "reproducible NLP system and model documentation", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "oral"],
    concentrationKey: "intelligent-systems",
    resource: {
      slug: "stanford-cs224n",
      title: "CS224N: Natural Language Processing with Deep Learning",
      provider: "Stanford University",
      url: "https://web.stanford.edu/class/cs224n/",
      kind: "course",
      authors: ["Christopher Manning", "Stanford CS224N staff"],
    },
  },
  {
    key: "parallel-computing",
    code: "CS634",
    slug: "parallel-computing",
    title: "Parallel Computing",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Parallel architectures, shared and distributed memory, locality, decomposition, communication, synchronization, and measurement.",
    primaryOutcome:
      "Parallelize, benchmark, and explain an application using defensible scaling and efficiency evidence.",
    prerequisiteKeys: ["operating-systems", "algorithms", "computer-architecture"],
    competencyKeys: ["systems", "algorithms"],
    topics: [
      { key: "parallel-machines-cost-models-and-limits-to-speedup", title: "parallel machines, cost models, and limits to speedup" },
      { key: "shared-memory-programming-and-synchronization", title: "shared-memory programming and synchronization" },
      { key: "data-locality-caches-and-memory-performance", title: "data locality, caches, and memory performance" },
      { key: "distributed-memory-programming-and-message-passing", title: "distributed-memory programming and message passing", assessmentPosition: "applied" },
      { key: "decomposition-load-balance-and-communication", title: "decomposition, load balance, and communication" },
      { key: "parallel-numerical-and-graph-kernels", title: "parallel numerical and graph kernels" },
      { key: "performance-measurement-profiling-and-scaling", title: "performance measurement, profiling, and scaling" },
      { key: "optimized-parallel-application-and-benchmark-report", title: "optimized parallel application and benchmark report", assessmentPosition: "final" },
    ],
    assessmentKinds: ["lab", "oral"],
    concentrationKey: "scalable-secure-systems",
    resource: {
      slug: "berkeley-cs267-parallel-applications",
      title: "CS267: Applications of Parallel Computers",
      provider: "University of California, Berkeley",
      url: "https://people.eecs.berkeley.edu/~demmel/cs267_Spr16/",
      kind: "course",
      authors: ["James Demmel", "Berkeley CS267 staff"],
    },
  },
  {
    key: "android-development",
    code: "CS635",
    slug: "android-application-development",
    title: "Android Application Development",
    term: 6,
    credits: 4,
    format: "studio",
    summary:
      "Kotlin, Compose UI, architecture, state, navigation, data, networking, accessibility, testing, and adaptive layouts.",
    primaryOutcome:
      "Ship a tested, accessible Android application with maintainable architecture and offline-aware data behavior.",
    prerequisiteKeys: ["software-engineering", "human-computer-interaction"],
    competencyKeys: ["software", "human-centered"],
    topics: [
      { key: "kotlin-fundamentals-and-android-project-structure", title: "Kotlin fundamentals and Android project structure" },
      { key: "compose-ui-layouts-and-theming", title: "Compose UI, layouts, and theming" },
      { key: "state-events-and-lifecycle-aware-design", title: "state, events, and lifecycle-aware design" },
      { key: "navigation-and-adaptive-interfaces", title: "navigation and adaptive interfaces", assessmentPosition: "applied" },
      { key: "architecture-view-models-and-data-layers", title: "architecture, view models, and data layers" },
      { key: "persistence-networking-and-offline-behavior", title: "persistence, networking, and offline behavior" },
      { key: "accessibility-testing-and-performance", title: "accessibility, testing, and performance" },
      { key: "release-preparation-and-a-complete-android-application", title: "release preparation and a complete Android application", assessmentPosition: "final" },
    ],
    assessmentKinds: ["project", "presentation"],
    concentrationKey: "interactive-applications",
    resource: {
      slug: "android-basics-with-compose",
      title: "Android Basics with Compose",
      provider: "Android Developers",
      url: "https://developer.android.com/courses/android-basics-compose/course",
      kind: "course",
      authors: ["Google Android Developers"],
    },
  },
  {
    key: "applied-cryptography",
    code: "CS636",
    slug: "applied-cryptography",
    title: "Applied Cryptography",
    term: 6,
    credits: 4,
    format: "theory",
    summary:
      "Encryption, authentication, public-key systems, key exchange, signatures, protocol composition, and implementation hazards.",
    primaryOutcome:
      "Select and analyze cryptographic constructions without inventing protocols or overstating security guarantees.",
    prerequisiteKeys: ["computer-security", "discrete-mathematics", "algorithms"],
    competencyKeys: ["security", "mathematics"],
    topics: [
      { key: "security-definitions-adversaries-and-threat-models", title: "security definitions, adversaries, and threat models" },
      { key: "one-time-pads-stream-ciphers-and-pseudorandomness", title: "one-time pads, stream ciphers, and pseudorandomness" },
      { key: "block-ciphers-and-modes-of-operation", title: "block ciphers and modes of operation" },
      { key: "message-authentication-and-authenticated-encryption", title: "message authentication and authenticated encryption", assessmentPosition: "applied" },
      { key: "hash-functions-and-password-storage", title: "hash functions and password storage" },
      { key: "public-key-encryption-and-number-theoretic-foundations", title: "public-key encryption and number-theoretic foundations" },
      { key: "key-exchange-digital-signatures-and-certificates", title: "key exchange, digital signatures, and certificates" },
      { key: "protocol-composition-implementation-failures-and-a-security-analysis", title: "protocol composition, implementation failures, and a security analysis", assessmentPosition: "final" },
    ],
    assessmentKinds: ["problem set", "oral"],
    concentrationKey: "scalable-secure-systems",
    resource: {
      slug: "stanford-online-cryptography",
      title: "Online Cryptography Course",
      provider: "Stanford University",
      url: "https://crypto.stanford.edu/~dabo/courses/OnlineCrypto/",
      kind: "course",
      authors: ["Dan Boneh"],
    },
  },
] as const satisfies readonly ComputerScienceCourseSpec[];
