/**
 * Stable identities assigned once to the original Electrical Engineering seed.
 *
 * Human-readable codes and titles are lookup keys for this import manifest,
 * not the public identity of a course or resource. They may change in later
 * published versions without changing these IDs.
 */
export const eeCourseIdsByLegacyCode = {
  MATH101: "crs_ee_001",
  PHYS101: "crs_ee_002",
  CS101: "crs_ee_003",
  EE101: "crs_ee_004",
  HUM101: "crs_ee_005",
  MATH102: "crs_ee_006",
  PHYS102: "crs_ee_007",
  CS102: "crs_ee_008",
  EE102: "crs_ee_009",
  HUM102: "crs_ee_010",
  MATH201: "crs_ee_011",
  EE201: "crs_ee_012",
  EE202: "crs_ee_013",
  EE203: "crs_ee_014",
  SCI201: "crs_ee_015",
  MATH202: "crs_ee_016",
  EE204: "crs_ee_017",
  EE205: "crs_ee_018",
  EE206: "crs_ee_019",
  HUM201: "crs_ee_020",
  EE301: "crs_ee_021",
  EE302: "crs_ee_022",
  EE303: "crs_ee_023",
  EE304: "crs_ee_024",
  CAP401: "crs_ee_025",
  EE306: "crs_ee_026",
  SYS401: "crs_ee_027",
  ENT401: "crs_ee_028",
  CAP402: "crs_ee_029",
} as const;

export const eeSpecializationCourseIds = {
  chips: ["crs_ee_chip_401", "crs_ee_chip_402"],
  signals: ["crs_ee_signal_401", "crs_ee_signal_402"],
  robotics: ["crs_ee_robot_401", "crs_ee_robot_402"],
  energy: ["crs_ee_energy_401", "crs_ee_energy_402"],
} as const;

export const eeResourceIdsByLegacyTitle: Record<string, string> = {
  "Introduction to Computer Science and Programming in Python": "res_ee_001",
  "Introduction to C and C++": "res_ee_002",
  "Mathematics for Computer Science": "res_ee_003",
  "Introduction to Algorithms": "res_ee_004",
  "Single Variable Calculus": "res_ee_005",
  "Multivariable Calculus": "res_ee_006",
  "Linear Algebra": "res_ee_007",
  "Differential Equations": "res_ee_008",
  "Probabilistic Systems Analysis and Applied Probability": "res_ee_009",
  "Classical Mechanics": "res_ee_010",
  "Physics II: Electricity and Magnetism": "res_ee_011",
  "The Feynman Lectures on Physics": "res_ee_012",
  "Circuits and Electronics": "res_ee_013",
  "Lessons in Electric Circuits": "res_ee_014",
  "Analog Electronic Circuits": "res_ee_015",
  "Signals and Systems": "res_ee_016",
  "The Scientist and Engineer's Guide to Digital Signal Processing": "res_ee_017",
  "The Fourier Transform and Its Applications": "res_ee_018",
  "Digital Signal Processing (NPTEL)": "res_ee_019",
  "Computation Structures": "res_ee_020",
  "Build a Modern Computer from First Principles": "res_ee_021",
  "Microelectronic Devices and Circuits": "res_ee_022",
  "Feedback Systems: An Introduction for Scientists and Engineers": "res_ee_023",
  "Electronic Feedback Systems": "res_ee_024",
  "Electromagnetics and Applications": "res_ee_025",
  "Digital Communication Systems": "res_ee_026",
  "An Introduction to Information Theory": "res_ee_027",
  "Microwave Engineering": "res_ee_028",
  "Introduction to Electric Power Systems": "res_ee_029",
  "Power Electronics": "res_ee_030",
  "Embedded System Design with ARM": "res_ee_031",
  "PhET Circuit Construction Kit: DC": "res_ee_032",
  CircuitJS1: "res_ee_033",
  LTspice: "res_ee_034",
  ngspice: "res_ee_035",
  KiCad: "res_ee_036",
  "GNU Octave": "res_ee_037",
  SciPy: "res_ee_038",
  Wokwi: "res_ee_039",
  Verilator: "res_ee_040",
  "GNU Radio": "res_ee_041",
  "ROS 2 Documentation": "res_ee_042",
  "Webots User Guide": "res_ee_043",
  OpenModelica: "res_ee_044",
  "RISC-V ISA Specifications": "res_ee_045",
  "IEEE Code of Ethics": "res_ee_046",
  "Engineering Ethics": "res_ee_047",
  "Science Writing and New Media": "res_ee_048",
  "Writing Guide with Handbook": "res_ee_049",
  "Introductory Analog Electronics Laboratory": "res_ee_050",
  "Introductory Digital Systems Laboratory": "res_ee_051",
  "Introduction to Electrical Engineering and Computer Science I": "res_ee_052",
  "Calculus Volume 1": "res_ee_053",
  "Calculus Volume 3": "res_ee_054",
  "University Physics Volume 1": "res_ee_055",
  "University Physics Volume 2": "res_ee_056",
  "Science, Technology, and World": "res_ee_057",
  "Social and Ethical Responsibilities of Computing": "res_ee_058",
  "Introduction to Technology and Policy": "res_ee_059",
  "Introduction to Solid State Chemistry": "res_ee_060",
  "Chemistry 2e": "res_ee_061",
  "Digital Signal Processing": "res_ee_062",
  "Principles of Digital Communications I": "res_ee_063",
  "Analysis and Design of Digital Integrated Circuits": "res_ee_064",
  "Product Engineering Process": "res_ee_065",
  "Prototypes to Products": "res_ee_066",
  "NASA Systems Engineering Handbook": "res_ee_067",
  "Modern Robotics": "res_ee_068",
  "Underactuated Robotics": "res_ee_069",
  "python-control": "res_ee_070",
  Yosys: "res_ee_071",
  "OpenLane 2": "res_ee_072",
  "SkyWater PDK Documentation": "res_ee_073",
  "scikit-rf": "res_ee_074",
  "OpenDSS Basic Examples": "res_ee_075",
  "Principles of Management": "res_ee_076",
  Entrepreneurship: "res_ee_077",
  "Zotero Quick Start Guide": "res_ee_078",
};
