import type {
  AssessmentKind,
  PublishedCourseVersion,
  ResourceKind,
} from "../../domain/catalog";

type EightTopics = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];

export type ComputerScienceCourseSpec = {
  readonly key: string;
  readonly code: string;
  readonly slug: string;
  readonly title: string;
  readonly term: 1 | 2 | 3 | 4 | 5 | 6;
  readonly credits: number;
  readonly format: PublishedCourseVersion["format"];
  readonly summary: string;
  readonly primaryOutcome: string;
  readonly prerequisiteKeys: readonly string[];
  readonly competencyKeys: readonly string[];
  readonly topics: EightTopics;
  readonly assessmentKinds?: readonly [AssessmentKind, AssessmentKind];
  readonly concentrationKey?: "intelligent-systems" | "scalable-secure-systems" | "interactive-applications";
  readonly resource: {
    readonly slug: string;
    readonly title: string;
    readonly provider: string;
    readonly url: string;
    readonly kind: ResourceKind;
    readonly authors: readonly string[];
  };
};

export const computerScienceCourseSpecs = [
  {
    key: "programming-1",
    code: "CS101",
    slug: "programming-1",
    title: "Programming I: Computational Problem Solving",
    term: 1,
    credits: 4,
    format: "studio",
    summary:
      "Python programming, decomposition, testing, debugging, files, regular expressions, and object-oriented design.",
    primaryOutcome:
      "Design, test, document, and defend a program that turns a real problem into reliable software.",
    prerequisiteKeys: [],
    competencyKeys: ["programming", "software"],
    topics: [
      "functions, variables, and expressions",
      "conditionals and Boolean reasoning",
      "loops, invariants, and iteration",
      "exceptions and systematic debugging",
      "libraries, APIs, and dependency choices",
      "unit tests and test design",
      "files, regular expressions, and data validation",
      "classes, composition, and a final Python application",
    ],
    resource: {
      slug: "cs50-introduction-to-programming-with-python",
      title: "CS50’s Introduction to Programming with Python",
      provider: "Harvard University CS50",
      url: "https://cs50.harvard.edu/python/",
      kind: "course",
      authors: ["David J. Malan", "Harvard CS50 staff"],
    },
  },
  {
    key: "discrete-mathematics",
    code: "MATH110",
    slug: "discrete-mathematics-for-computing",
    title: "Discrete Mathematics for Computing",
    term: 1,
    credits: 4,
    format: "theory",
    summary:
      "Proof, sets, relations, graphs, state machines, modular arithmetic, counting, and discrete probability.",
    primaryOutcome:
      "Write sound proofs and apply discrete structures to algorithms, software, and finite systems.",
    prerequisiteKeys: [],
    competencyKeys: ["mathematics", "algorithms"],
    topics: [
      "propositions, predicates, and proof structure",
      "sets, functions, relations, and induction",
      "strong induction and recursive definitions",
      "graphs, trees, and graph invariants",
      "state machines and invariants",
      "number theory and modular arithmetic",
      "counting, recurrences, and asymptotics",
      "discrete probability and cumulative proof practice",
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-mathematics-for-computer-science",
      title: "Mathematics for Computer Science",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/",
      kind: "course",
      authors: ["Albert R. Meyer", "Adam Chlipala"],
    },
  },
  {
    key: "calculus",
    code: "MATH120",
    slug: "calculus-for-computing",
    title: "Calculus for Computing",
    term: 1,
    credits: 4,
    format: "theory",
    summary:
      "Single-variable differentiation, integration, approximation, optimization, differential equations, and series.",
    primaryOutcome:
      "Use calculus to model change, optimize systems, and explain numerical approximations used in computing.",
    prerequisiteKeys: [],
    competencyKeys: ["mathematics"],
    topics: [
      "functions, limits, and continuity",
      "derivatives from definitions and rules",
      "linearization and numerical approximation",
      "optimization and related rates",
      "definite integrals and accumulation",
      "the fundamental theorem and applications",
      "integration methods and differential models",
      "Taylor series, error, and cumulative modeling",
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-single-variable-calculus",
      title: "Single Variable Calculus",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/",
      kind: "course",
      authors: ["David Jerison", "MIT Mathematics"],
    },
  },
  {
    key: "systems-foundations",
    code: "CS110",
    slug: "computer-systems-foundations",
    title: "Computer Systems Foundations",
    term: 1,
    credits: 4,
    format: "laboratory",
    summary:
      "C programming, memory, data representation, algorithms, SQL, and the layers connecting source code to machines.",
    primaryOutcome:
      "Explain how programs use memory and implement a tested systems-oriented application in C.",
    prerequisiteKeys: ["programming-1"],
    competencyKeys: ["programming", "systems"],
    topics: [
      "computational thinking and C toolchains",
      "C control flow, functions, and compilation",
      "arrays, strings, and data representation",
      "algorithmic costs and empirical measurement",
      "pointers, memory layout, and allocation",
      "linked structures and memory safety",
      "SQL and durable data",
      "systems integration and a cumulative C build",
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "cs50-introduction-to-computer-science",
      title: "CS50’s Introduction to Computer Science",
      provider: "Harvard University CS50",
      url: "https://cs50.harvard.edu/x/",
      kind: "course",
      authors: ["David J. Malan", "Harvard CS50 staff"],
    },
  },
  {
    key: "technical-communication",
    code: "PROF110",
    slug: "technical-communication",
    title: "Technical Communication for Computing",
    term: 1,
    credits: 4,
    format: "seminar",
    summary:
      "Audience analysis, clear sentences, document structure, evidence, diagrams, accessibility, and technical review.",
    primaryOutcome:
      "Produce concise technical documentation whose claims, procedures, and design decisions can be checked.",
    prerequisiteKeys: [],
    competencyKeys: ["professional", "software"],
    topics: [
      "audience, purpose, and scope",
      "terminology, active voice, and clear sentences",
      "paragraphs, lists, and information hierarchy",
      "procedures, examples, and reproducible instructions",
      "Markdown, code samples, and document tooling",
      "diagrams, tables, captions, and accessibility",
      "source evaluation, citation, and uncertainty",
      "peer review and a polished technical guide",
    ],
    assessmentKinds: ["portfolio", "presentation"],
    resource: {
      slug: "google-technical-writing-one",
      title: "Technical Writing One",
      provider: "Google for Developers",
      url: "https://developers.google.com/tech-writing/one",
      kind: "course",
      authors: ["Google Technical Writing team"],
    },
  },
  {
    key: "data-structures",
    code: "CS201",
    slug: "data-structures",
    title: "Data Structures and Abstractions",
    term: 2,
    credits: 4,
    format: "laboratory",
    summary:
      "Abstract data types, lists, trees, hash tables, priority queues, graphs, sorting, and amortized analysis.",
    primaryOutcome:
      "Select, implement, test, and empirically evaluate data structures for a stated workload.",
    prerequisiteKeys: ["programming-1", "discrete-mathematics"],
    competencyKeys: ["programming", "algorithms"],
    topics: [
      "interfaces, abstraction, and asymptotic cost",
      "arrays, linked lists, stacks, and queues",
      "testing, invariants, and encapsulation",
      "hash tables and collision strategies",
      "trees, traversals, and search trees",
      "priority queues, heaps, and disjoint sets",
      "graphs and graph representations",
      "sorting, amortized analysis, and a data-structure library",
    ],
    assessmentKinds: ["project", "exam"],
    resource: {
      slug: "berkeley-cs61b-data-structures",
      title: "CS 61B: Data Structures",
      provider: "University of California, Berkeley EECS",
      url: "https://people.eecs.berkeley.edu/~jrs/61b/",
      kind: "course",
      authors: ["Jonathan Shewchuk"],
    },
  },
  {
    key: "computer-architecture",
    code: "CS210",
    slug: "computer-architecture",
    title: "Computer Architecture: From Logic to Machine",
    term: 2,
    credits: 4,
    format: "laboratory",
    summary:
      "Boolean logic, hardware description, ALUs, memory, instruction sets, assemblers, virtual machines, and operating systems.",
    primaryOutcome:
      "Build and explain a functioning computer stack from logic gates through executable programs.",
    prerequisiteKeys: ["systems-foundations", "discrete-mathematics"],
    competencyKeys: ["systems"],
    topics: [
      "Boolean functions and elementary logic gates",
      "adders, ALUs, and combinational chips",
      "registers, memory, and sequential logic",
      "machine language and instruction-set design",
      "CPU and computer integration",
      "assembler design and implementation",
      "virtual machines, parsing, and code generation",
      "operating-system services and full-stack demonstration",
    ],
    assessmentKinds: ["lab", "presentation"],
    resource: {
      slug: "nand2tetris-course",
      title: "Nand2Tetris Course and Projects",
      provider: "Nand2Tetris",
      url: "https://www.nand2tetris.org/course",
      kind: "course",
      authors: ["Noam Nisan", "Shimon Schocken"],
    },
  },
  {
    key: "linear-algebra",
    code: "MATH210",
    slug: "linear-algebra",
    title: "Linear Algebra for Computer Science",
    term: 2,
    credits: 4,
    format: "theory",
    summary:
      "Linear systems, vector spaces, orthogonality, eigenvalues, decompositions, and computational applications.",
    primaryOutcome:
      "Formulate and solve vector and matrix models while explaining numerical and geometric meaning.",
    prerequisiteKeys: ["calculus"],
    competencyKeys: ["mathematics", "ai-data"],
    topics: [
      "linear systems and elimination",
      "matrix operations, inverses, and factorization",
      "vector spaces, subspaces, and basis",
      "orthogonality and least squares",
      "determinants and volume",
      "eigenvalues and eigenvectors",
      "singular values and low-rank approximation",
      "numerical linear algebra in a computing application",
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-linear-algebra",
      title: "Linear Algebra",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/",
      kind: "course",
      authors: ["Gilbert Strang"],
    },
  },
  {
    key: "probability",
    code: "STAT210",
    slug: "probability-for-computing",
    title: "Probability for Computing",
    term: 2,
    credits: 4,
    format: "theory",
    summary:
      "Counting, conditional probability, random variables, expectation, common distributions, and simulation.",
    primaryOutcome:
      "Build, calculate, simulate, and critique probabilistic models used in algorithms and data systems.",
    prerequisiteKeys: ["calculus", "discrete-mathematics"],
    competencyKeys: ["mathematics", "ai-data"],
    topics: [
      "counting and probability spaces",
      "conditional probability and Bayes' rule",
      "independence and probabilistic reasoning",
      "discrete random variables and expectation",
      "continuous distributions and transformations",
      "joint distributions, covariance, and conditioning",
      "law of large numbers and central limit behavior",
      "simulation, estimation, and a cumulative probability model",
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "harvard-statistics-110",
      title: "Statistics 110: Probability",
      provider: "Harvard University",
      url: "https://stat110.hsites.harvard.edu/",
      kind: "course",
      authors: ["Joe Blitzstein"],
    },
  },
  {
    key: "web-engineering",
    code: "CS220",
    slug: "web-engineering",
    title: "Web Engineering",
    term: 2,
    credits: 4,
    format: "studio",
    summary:
      "Semantic HTML, CSS, JavaScript, accessibility, HTTP, browser APIs, testing, performance, and deployment.",
    primaryOutcome:
      "Ship an accessible, standards-based web application and justify its architecture and performance.",
    prerequisiteKeys: ["programming-1", "technical-communication"],
    competencyKeys: ["software", "human-centered"],
    topics: [
      "web standards, semantic HTML, and document structure",
      "CSS layout, responsive design, and maintainability",
      "JavaScript, the DOM, and event-driven behavior",
      "forms, validation, accessibility, and inclusive interaction",
      "HTTP, fetch, APIs, and asynchronous control flow",
      "client state, components, and architecture",
      "testing, security basics, and performance",
      "deployment, observability, and a production-ready application",
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "mdn-learn-web-development",
      title: "Learn Web Development",
      provider: "MDN Web Docs",
      url: "https://developer.mozilla.org/en-US/docs/Learn_web_development",
      kind: "course",
      authors: ["MDN contributors"],
    },
  },
  {
    key: "algorithms",
    code: "CS301",
    slug: "algorithm-design-and-analysis",
    title: "Algorithm Design and Analysis",
    term: 3,
    credits: 4,
    format: "theory",
    summary:
      "Algorithmic modeling, asymptotic analysis, sorting, graph algorithms, dynamic programming, and complexity tradeoffs.",
    primaryOutcome:
      "Design, prove, implement, and measure algorithms while stating the limits of each approach.",
    prerequisiteKeys: ["data-structures", "discrete-mathematics"],
    competencyKeys: ["algorithms", "mathematics"],
    topics: [
      "computational models and asymptotic analysis",
      "recurrences, divide-and-conquer, and sorting",
      "hashing and randomized algorithms",
      "binary search trees and augmentation",
      "breadth-first and depth-first graph search",
      "shortest paths and weighted graphs",
      "dynamic programming and greedy design",
      "complexity evidence and a cumulative algorithm portfolio",
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-introduction-to-algorithms",
      title: "Introduction to Algorithms",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/",
      kind: "course",
      authors: ["Erik Demaine", "Srini Devadas"],
    },
  },
  {
    key: "operating-systems",
    code: "CS310",
    slug: "operating-systems",
    title: "Operating Systems",
    term: 3,
    credits: 4,
    format: "laboratory",
    summary:
      "Processes, scheduling, virtual memory, concurrency, synchronization, storage, file systems, and protection.",
    primaryOutcome:
      "Implement and test core operating-system mechanisms and explain their safety and performance tradeoffs.",
    prerequisiteKeys: ["data-structures", "computer-architecture"],
    competencyKeys: ["systems", "security"],
    topics: [
      "processes, system calls, and direct execution",
      "CPU scheduling and measurable policy tradeoffs",
      "address spaces and memory APIs",
      "paging, translation, and virtual memory",
      "threads, locks, condition variables, and semaphores",
      "concurrency bugs and event-driven systems",
      "storage devices, files, and file-system implementation",
      "persistence, integrity, protection, and a systems lab",
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "operating-systems-three-easy-pieces",
      title: "Operating Systems: Three Easy Pieces",
      provider: "University of Wisconsin–Madison authors",
      url: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
      kind: "textbook",
      authors: ["Remzi H. Arpaci-Dusseau", "Andrea C. Arpaci-Dusseau"],
    },
  },
  {
    key: "database-systems",
    code: "CS320",
    slug: "database-systems",
    title: "Database Systems",
    term: 3,
    credits: 4,
    format: "laboratory",
    summary:
      "Relational modeling, SQL, storage, indexes, query execution, transactions, concurrency control, and recovery.",
    primaryOutcome:
      "Design a sound relational system and implement selected database internals with measured behavior.",
    prerequisiteKeys: ["data-structures", "systems-foundations"],
    competencyKeys: ["data", "systems"],
    topics: [
      "data models, relational algebra, and SQL",
      "schema design, dependencies, and normalization",
      "storage models, pages, and buffer pools",
      "indexes, trees, hashing, and filters",
      "query execution, joins, sorting, and aggregation",
      "query planning and optimization",
      "transactions and concurrency control",
      "logging, recovery, and a database implementation review",
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "cmu-intro-to-database-systems",
      title: "15-445/645: Intro to Database Systems",
      provider: "Carnegie Mellon University Database Group",
      url: "https://15445.courses.cs.cmu.edu/spring2026/",
      kind: "course",
      authors: ["Andy Pavlo", "Jignesh Patel", "CMU Database Group"],
    },
  },
  {
    key: "software-engineering",
    code: "CS330",
    slug: "software-engineering",
    title: "Software Engineering",
    term: 3,
    credits: 4,
    format: "studio",
    summary:
      "Sustainable design, testing, review, dependency management, APIs, build systems, teamwork, and maintenance.",
    primaryOutcome:
      "Evolve a team software system using explicit requirements, tests, review, documentation, and maintenance evidence.",
    prerequisiteKeys: ["data-structures", "web-engineering"],
    competencyKeys: ["software", "professional"],
    topics: [
      "software engineering over time and scale",
      "team culture, knowledge sharing, and ownership",
      "style, readability, and documentation",
      "testing strategy and test maintainability",
      "dependency management, APIs, and compatibility",
      "version control, code review, and change management",
      "build systems, continuous integration, and release",
      "technical debt, sustainability, and a maintained team system",
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "software-engineering-at-google",
      title: "Software Engineering at Google",
      provider: "Google / Abseil",
      url: "https://abseil.io/resources/swe-book",
      kind: "textbook",
      authors: ["Titus Winters", "Tom Manshreck", "Hyrum Wright"],
    },
  },
  {
    key: "computer-networks",
    code: "CS340",
    slug: "computer-networks",
    title: "Computer Networks",
    term: 3,
    credits: 4,
    format: "laboratory",
    summary:
      "Layering, packet switching, reliable transport, routing, naming, congestion, network programming, and measurement.",
    primaryOutcome:
      "Implement a reliable transport component and diagnose network behavior from packet-level evidence.",
    prerequisiteKeys: ["systems-foundations", "data-structures"],
    competencyKeys: ["networks", "systems"],
    topics: [
      "network architecture, layering, and packet switching",
      "application protocols, naming, and HTTP",
      "sockets, streams, and network programming",
      "reliable byte streams and retransmission",
      "IP, forwarding, addressing, and routing",
      "congestion control and shared capacity",
      "link layers, local networks, and measurement",
      "network security, operations, and a transport implementation",
    ],
    assessmentKinds: ["lab", "exam"],
    resource: {
      slug: "stanford-cs144-networking",
      title: "CS 144: Introduction to Computer Networking",
      provider: "Stanford University",
      url: "https://cs144.github.io/",
      kind: "course",
      authors: ["Keith Winstein", "Stanford CS144 staff"],
    },
  },
  {
    key: "theory-of-computation",
    code: "CS401",
    slug: "theory-of-computation",
    title: "Theory of Computation",
    term: 4,
    credits: 4,
    format: "theory",
    summary:
      "Automata, regular and context-free languages, computability, reductions, complexity, and NP-completeness.",
    primaryOutcome:
      "Prove what computational models can and cannot decide and classify the complexity of representative problems.",
    prerequisiteKeys: ["algorithms", "discrete-mathematics"],
    competencyKeys: ["theory", "mathematics"],
    topics: [
      "finite automata and regular languages",
      "regular expressions, closure, and pumping arguments",
      "context-free grammars and pushdown automata",
      "Turing machines and recognizable languages",
      "decidability and undecidability",
      "mapping reductions and proof technique",
      "time complexity, P, and NP",
      "NP-completeness and cumulative theory proofs",
    ],
    assessmentKinds: ["problem set", "exam"],
    resource: {
      slug: "mit-automata-computability-complexity",
      title: "Automata, Computability, and Complexity",
      provider: "MIT OpenCourseWare",
      url: "https://ocw.mit.edu/courses/6-045j-automata-computability-and-complexity-spring-2011/",
      kind: "course",
      authors: ["Scott Aaronson"],
    },
  },
  {
    key: "programming-languages",
    code: "CS410",
    slug: "programming-languages",
    title: "Programming Languages",
    term: 4,
    credits: 4,
    format: "laboratory",
    summary:
      "Syntax, interpreters, scope, functions, state, types, objects, memory, and language-level tradeoffs.",
    primaryOutcome:
      "Implement interpreters and type checkers while comparing language semantics through executable evidence.",
    prerequisiteKeys: ["data-structures", "discrete-mathematics"],
    competencyKeys: ["programming", "theory"],
    topics: [
      "syntax, abstract syntax trees, and evaluation",
      "substitution, environments, and scope",
      "functions, closures, and recursion",
      "state, mutation, and stores",
      "data abstraction and object models",
      "static types, type checking, and inference",
      "memory management and language implementation",
      "language design comparison and an interpreter portfolio",
    ],
    assessmentKinds: ["lab", "oral"],
    resource: {
      slug: "programming-languages-application-interpretation",
      title: "Programming Languages: Application and Interpretation",
      provider: "Brown University PLT",
      url: "https://www.plai.org/",
      kind: "textbook",
      authors: ["Shriram Krishnamurthi"],
    },
  },
  {
    key: "compilers",
    code: "CS420",
    slug: "compilers-and-language-implementation",
    title: "Compilers and Language Implementation",
    term: 4,
    credits: 4,
    format: "laboratory",
    summary:
      "Scanning, parsing, syntax trees, semantic analysis, bytecode, virtual machines, closures, garbage collection, and optimization.",
    primaryOutcome:
      "Build, test, profile, and explain an interpreter and bytecode virtual machine for a small language.",
    prerequisiteKeys: ["programming-languages", "theory-of-computation"],
    competencyKeys: ["programming", "systems", "theory"],
    topics: [
      "language design, tokens, and scanning",
      "recursive-descent parsing and syntax trees",
      "expression evaluation and runtime errors",
      "statements, control flow, functions, and closures",
      "name resolution, classes, and inheritance",
      "bytecode representation and virtual-machine execution",
      "values, memory, hash tables, and garbage collection",
      "optimization, diagnostics, and a complete language implementation",
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "crafting-interpreters",
      title: "Crafting Interpreters",
      provider: "Robert Nystrom",
      url: "https://craftinginterpreters.com/",
      kind: "textbook",
      authors: ["Robert Nystrom"],
    },
  },
  {
    key: "computer-security",
    code: "CS430",
    slug: "computer-security",
    title: "Computer Security",
    term: 4,
    credits: 4,
    format: "laboratory",
    summary:
      "Threat modeling, authentication, access control, web vulnerabilities, secure coding, testing, and incident analysis.",
    primaryOutcome:
      "Find, explain, safely reproduce, and remediate vulnerabilities in an isolated legal training environment.",
    prerequisiteKeys: ["operating-systems", "computer-networks", "web-engineering"],
    competencyKeys: ["security", "systems"],
    topics: [
      "security goals, threat models, and attack surfaces",
      "authentication, sessions, and access control",
      "injection and server-side input handling",
      "cross-site scripting and browser trust boundaries",
      "request forgery, cross-origin policy, and clickjacking",
      "file, path, command, and server-side request vulnerabilities",
      "business logic, race conditions, and API security",
      "testing methodology, remediation, and an ethical security report",
    ],
    assessmentKinds: ["lab", "oral"],
    resource: {
      slug: "portswigger-web-security-academy",
      title: "Web Security Academy",
      provider: "PortSwigger",
      url: "https://portswigger.net/web-security",
      kind: "course",
      authors: ["PortSwigger Web Security Academy"],
    },
  },
  {
    key: "human-computer-interaction",
    code: "CS440",
    slug: "human-computer-interaction",
    title: "Human–Computer Interaction",
    term: 4,
    credits: 4,
    format: "studio",
    summary:
      "Human-centered research, task analysis, ideation, prototyping, usability testing, accessibility, and iterative design.",
    primaryOutcome:
      "Research, prototype, test, and revise an interactive system with traceable evidence from real participants.",
    prerequisiteKeys: ["web-engineering", "technical-communication"],
    competencyKeys: ["human-centered", "professional"],
    topics: [
      "human-centered design and ethical research",
      "interviews, observation, and task analysis",
      "personas, scenarios, requirements, and design goals",
      "sketching, storyboards, and design alternatives",
      "low-fidelity prototypes and heuristic evaluation",
      "interactive prototypes and accessibility",
      "usability studies, measures, and analysis",
      "iteration, design rationale, and a tested product prototype",
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "uw-cse440-introduction-to-hci",
      title: "CSE 440: Introduction to HCI",
      provider: "University of Washington",
      url: "https://courses.cs.washington.edu/courses/cse440/24au/",
      kind: "course",
      authors: ["University of Washington CSE 440 staff"],
    },
  },
  {
    key: "artificial-intelligence",
    code: "CS501",
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    term: 5,
    credits: 4,
    format: "laboratory",
    summary:
      "Search, adversarial reasoning, constraint satisfaction, probability, decision processes, inference, and learning.",
    primaryOutcome:
      "Implement and compare intelligent-agent techniques while stating assumptions, failure modes, and ethical limits.",
    prerequisiteKeys: ["algorithms", "probability"],
    competencyKeys: ["ai-data", "algorithms"],
    topics: [
      "agents, state spaces, and uninformed search",
      "heuristics, A-star, and search quality",
      "games, minimax, and adversarial search",
      "constraint-satisfaction problems",
      "probability, Bayes nets, and inference",
      "Markov models and decision processes",
      "reinforcement learning and value estimation",
      "machine-learning overview and an intelligent-agent project",
    ],
    assessmentKinds: ["project", "exam"],
    resource: {
      slug: "berkeley-cs188-textbook",
      title: "Introduction to Artificial Intelligence",
      provider: "University of California, Berkeley CS188",
      url: "https://inst.eecs.berkeley.edu/~cs188/textbook/",
      kind: "textbook",
      authors: ["Berkeley CS188 course staff"],
    },
  },
  {
    key: "machine-learning",
    code: "CS510",
    slug: "machine-learning",
    title: "Machine Learning",
    term: 5,
    credits: 4,
    format: "laboratory",
    summary:
      "Regression, classification, data preparation, generalization, neural networks, embeddings, fairness, and production systems.",
    primaryOutcome:
      "Build and evaluate a reproducible machine-learning pipeline with honest metrics and model limitations.",
    prerequisiteKeys: ["linear-algebra", "probability", "programming-1"],
    competencyKeys: ["ai-data", "mathematics", "professional"],
    topics: [
      "problem framing, data splits, and baselines",
      "linear regression, loss, and gradient descent",
      "logistic regression, classification, and metrics",
      "numerical and categorical feature engineering",
      "generalization, overfitting, and regularization",
      "neural networks and representation learning",
      "production ML systems and monitoring",
      "fairness, error analysis, and a reproducible model card",
    ],
    assessmentKinds: ["project", "oral"],
    resource: {
      slug: "google-machine-learning-crash-course",
      title: "Machine Learning Crash Course",
      provider: "Google for Developers",
      url: "https://developers.google.com/machine-learning/crash-course",
      kind: "course",
      authors: ["Google Machine Learning Education"],
    },
  },
  {
    key: "distributed-systems",
    code: "CS520",
    slug: "distributed-systems",
    title: "Distributed Systems",
    term: 5,
    credits: 4,
    format: "laboratory",
    summary:
      "Remote communication, failure, consensus, replication, consistency, transactions, distributed storage, and observability.",
    primaryOutcome:
      "Implement and test replicated services under delay, concurrency, restart, and partial failure.",
    prerequisiteKeys: ["operating-systems", "computer-networks", "database-systems"],
    competencyKeys: ["networks", "systems", "data"],
    topics: [
      "distributed-system models and remote procedure calls",
      "time, ordering, concurrency, and failure",
      "primary-backup replication and state machines",
      "consensus and the Raft protocol",
      "fault-tolerant key-value services",
      "sharding, reconfiguration, and transactions",
      "consistency models and distributed storage",
      "measurement, testing under failure, and a replicated service",
    ],
    assessmentKinds: ["lab", "oral"],
    resource: {
      slug: "mit-distributed-systems",
      title: "6.5840: Distributed Systems",
      provider: "MIT PDOS / CSAIL",
      url: "https://pdos.csail.mit.edu/6.824/",
      kind: "course",
      authors: ["MIT PDOS faculty and course staff"],
    },
  },
  {
    key: "computing-ethics",
    code: "CS530",
    slug: "ethics-of-computing-and-ai",
    title: "Ethics of Computing and AI",
    term: 5,
    credits: 4,
    format: "seminar",
    summary:
      "Ethical reasoning, accountability, transparency, rights, fairness, professional responsibility, and sociotechnical analysis.",
    primaryOutcome:
      "Analyze a computing intervention using evidence, stakeholders, ethical frameworks, and actionable safeguards.",
    prerequisiteKeys: ["technical-communication"],
    competencyKeys: ["ethics", "professional"],
    topics: [
      "sociotechnical systems and ethical argument",
      "benefit, harm, non-maleficence, and uncertainty",
      "responsibility, accountability, and governance",
      "transparency, explanation, and contestability",
      "privacy, autonomy, and human rights",
      "fairness, discrimination, and measurement",
      "professional duties and responsible development",
      "case synthesis, safeguards, and a public ethics review",
    ],
    assessmentKinds: ["portfolio", "oral"],
    resource: {
      slug: "university-helsinki-ethics-of-ai",
      title: "Ethics of AI",
      provider: "University of Helsinki / MOOC.fi",
      url: "https://ethics-of-ai.mooc.fi/",
      kind: "course",
      authors: ["University of Helsinki Ethics of AI team"],
    },
  },
  {
    key: "capstone-1",
    code: "CS540",
    slug: "capstone-studio-1",
    title: "Capstone Studio I: Proposal and Prototype",
    term: 5,
    credits: 4,
    format: "capstone",
    summary:
      "Problem discovery, project scoping, engineering tools, architecture, risk, research, prototyping, and proposal defense.",
    primaryOutcome:
      "Define a consequential computing problem and defend a feasible, ethical, tested capstone plan and prototype.",
    prerequisiteKeys: ["software-engineering", "algorithms", "human-computer-interaction"],
    competencyKeys: ["capstone", "software", "professional"],
    topics: [
      "problem discovery, stakeholders, and evidence",
      "scope, success criteria, constraints, and non-goals",
      "command-line and development-environment reproducibility",
      "version control, collaboration, and project planning",
      "architecture options and risk spikes",
      "debugging, profiling, and prototype measurement",
      "security, ethics, accessibility, and failure planning",
      "proposal, prototype, schedule, and oral defense",
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "mit-missing-semester",
      title: "The Missing Semester of Your CS Education",
      provider: "MIT",
      url: "https://missing.csail.mit.edu/",
      kind: "course",
      authors: ["MIT Missing Semester instructors"],
    },
  },
  {
    key: "data-science",
    code: "CS601",
    slug: "data-science",
    title: "Data Science and Statistical Inference",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Data tables, visualization, sampling, estimation, hypothesis testing, prediction, uncertainty, and reproducibility.",
    primaryOutcome:
      "Conduct and communicate a reproducible data investigation without overstating what the evidence supports.",
    prerequisiteKeys: ["database-systems", "machine-learning", "probability"],
    competencyKeys: ["ai-data", "data", "professional"],
    topics: [
      "data-generating processes, tables, and reproducibility",
      "cleaning, transformation, and exploratory visualization",
      "sampling, empirical distributions, and simulation",
      "estimation, confidence intervals, and uncertainty",
      "hypothesis testing and error",
      "association, correlation, and linear prediction",
      "classification, evaluation, and fairness",
      "end-to-end investigation and an evidence-aware report",
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "computational-and-inferential-thinking",
      title: "Computational and Inferential Thinking",
      provider: "UC Berkeley Data 8",
      url: "https://inferentialthinking.com/",
      kind: "textbook",
      authors: ["Ani Adhikari", "John DeNero", "David Wagner"],
    },
  },
  {
    key: "research-methods",
    code: "CS610",
    slug: "computer-science-research-methods",
    title: "Computer Science Research Methods",
    term: 6,
    credits: 4,
    format: "seminar",
    summary:
      "Research questions, paper reading, literature search, method choice, validity, reproducibility, peer review, and proposals.",
    primaryOutcome:
      "Formulate a tractable research question and produce a critical literature review and reproducible study plan.",
    prerequisiteKeys: ["probability", "technical-communication", "algorithms"],
    competencyKeys: ["research", "professional", "mathematics"],
    topics: [
      "research questions, claims, contribution types, and paper reading",
      "potential outcomes, counterfactuals, and estimands",
      "randomized experiments, power, and common validity threats",
      "causal diagrams, confounding, and identification assumptions",
      "regression, diagnostics, and responsible interpretation",
      "benchmarks as measurement instruments",
      "quasi-experiments, reproducibility, and research ethics",
      "literature synthesis, analysis plans, and a defensible proposal",
    ],
    assessmentKinds: ["portfolio", "oral"],
    resource: {
      slug: "princeton-empirical-research-methods-cs",
      title: "COS 598D: Empirical Research Methods for CS",
      provider: "Princeton University",
      url: "https://humans.cs.princeton.edu/teaching/spring2026_empirical_methods.html",
      kind: "course",
      authors: ["Manoel Horta Ribeiro", "Princeton COS 598D course staff"],
    },
  },
  {
    key: "capstone-2",
    code: "CS620",
    slug: "capstone-studio-2",
    title: "Capstone Studio II: Build, Evaluate, and Defend",
    term: 6,
    credits: 4,
    format: "capstone",
    summary:
      "Iterative implementation, review, testing, evaluation, documentation, release, portfolio evidence, and public defense.",
    primaryOutcome:
      "Ship, evaluate, document, and publicly defend a substantial computing artifact and its limitations.",
    prerequisiteKeys: ["capstone-1", "research-methods"],
    competencyKeys: ["capstone", "software", "research", "professional"],
    topics: [
      "reconfirming requirements, risks, and evaluation plan",
      "vertical-slice implementation and continuous integration",
      "design review and evidence-driven reprioritization",
      "testing, security review, and accessibility review",
      "performance, reliability, and failure testing",
      "user or system evaluation and analysis",
      "documentation, release, reproducibility, and handoff",
      "final artifact, portfolio, retrospective, and public defense",
    ],
    assessmentKinds: ["project", "presentation"],
    resource: {
      slug: "google-engineering-practices-code-review",
      title: "Google Engineering Practices: Code Review",
      provider: "Google",
      url: "https://google.github.io/eng-practices/review/",
      kind: "documentation",
      authors: ["Google Engineering Practices team"],
    },
  },
  {
    key: "computer-graphics",
    code: "CS631",
    slug: "computer-graphics",
    title: "Computer Graphics",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Rasterization, sampling, transforms, meshes, geometry, ray tracing, materials, animation, and simulation.",
    primaryOutcome:
      "Implement a small rendering pipeline and explain visual quality, numerical, and performance tradeoffs.",
    prerequisiteKeys: ["algorithms", "linear-algebra"],
    competencyKeys: ["graphics", "programming", "mathematics"],
    topics: [
      "images as data, rasterization, and sampling",
      "transforms, coordinate systems, and texture mapping",
      "geometry processing and half-edge meshes",
      "curves, surfaces, and mesh editing",
      "ray generation, intersections, and acceleration",
      "lighting, materials, and global illumination",
      "animation, numerical integration, and simulation",
      "rendering-system evaluation and a graphics project",
    ],
    assessmentKinds: ["project", "presentation"],
    concentrationKey: "interactive-applications",
    resource: {
      slug: "berkeley-cs184-computer-graphics",
      title: "CS 184/284A: Computer Graphics",
      provider: "University of California, Berkeley",
      url: "https://cs184.eecs.berkeley.edu/sp25/",
      kind: "course",
      authors: ["Ren Ng", "Berkeley CS184 staff"],
    },
  },
  {
    key: "computer-vision",
    code: "CS632",
    slug: "computer-vision",
    title: "Deep Learning for Computer Vision",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Image classification, convolutional networks, optimization, recognition, detection, interpretation, and responsible evaluation.",
    primaryOutcome:
      "Train, diagnose, and communicate a computer-vision system with reproducible evidence and error analysis.",
    prerequisiteKeys: ["machine-learning", "linear-algebra"],
    competencyKeys: ["ai-data", "graphics"],
    topics: [
      "image classification and data-driven recognition",
      "linear classifiers, loss functions, and optimization",
      "neural networks and backpropagation",
      "convolutional architectures and training",
      "regularization, transfer learning, and augmentation",
      "detection, segmentation, and localization",
      "visualization, interpretation, bias, and robustness",
      "reproducible vision experiment and model report",
    ],
    assessmentKinds: ["project", "oral"],
    concentrationKey: "intelligent-systems",
    resource: {
      slug: "stanford-cs231n",
      title: "CS231n: Deep Learning for Computer Vision",
      provider: "Stanford University",
      url: "https://cs231n.stanford.edu/",
      kind: "course",
      authors: ["Stanford CS231n instructors and staff"],
    },
  },
  {
    key: "natural-language-processing",
    code: "CS633",
    slug: "natural-language-processing",
    title: "Natural Language Processing with Deep Learning",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Word vectors, sequence models, attention, transformers, language models, evaluation, bias, and deployment.",
    primaryOutcome:
      "Build and evaluate an NLP model while documenting data, linguistic, ethical, and deployment limitations.",
    prerequisiteKeys: ["machine-learning", "probability"],
    competencyKeys: ["ai-data", "professional"],
    topics: [
      "language structure, tokenization, and distributional meaning",
      "word vectors and representation geometry",
      "neural sequence models and recurrent networks",
      "attention and encoder-decoder models",
      "transformers and pretrained language models",
      "question answering, generation, and retrieval",
      "evaluation, hallucination, bias, and safety",
      "reproducible NLP system and model documentation",
    ],
    assessmentKinds: ["project", "oral"],
    concentrationKey: "intelligent-systems",
    resource: {
      slug: "stanford-cs224n",
      title: "CS224N: Natural Language Processing with Deep Learning",
      provider: "Stanford University",
      url: "https://web.stanford.edu/class/cs224n/",
      kind: "course",
      authors: ["Christopher Manning", "Stanford CS224N staff"],
    },
  },
  {
    key: "parallel-computing",
    code: "CS634",
    slug: "parallel-computing",
    title: "Parallel Computing",
    term: 6,
    credits: 4,
    format: "laboratory",
    summary:
      "Parallel architectures, shared and distributed memory, locality, decomposition, communication, synchronization, and measurement.",
    primaryOutcome:
      "Parallelize, benchmark, and explain an application using defensible scaling and efficiency evidence.",
    prerequisiteKeys: ["operating-systems", "algorithms", "computer-architecture"],
    competencyKeys: ["systems", "algorithms"],
    topics: [
      "parallel machines, cost models, and limits to speedup",
      "shared-memory programming and synchronization",
      "data locality, caches, and memory performance",
      "distributed-memory programming and message passing",
      "decomposition, load balance, and communication",
      "parallel numerical and graph kernels",
      "performance measurement, profiling, and scaling",
      "optimized parallel application and benchmark report",
    ],
    assessmentKinds: ["lab", "oral"],
    concentrationKey: "scalable-secure-systems",
    resource: {
      slug: "berkeley-cs267-parallel-applications",
      title: "CS267: Applications of Parallel Computers",
      provider: "University of California, Berkeley",
      url: "https://people.eecs.berkeley.edu/~demmel/cs267_Spr16/",
      kind: "course",
      authors: ["James Demmel", "Berkeley CS267 staff"],
    },
  },
  {
    key: "android-development",
    code: "CS635",
    slug: "android-application-development",
    title: "Android Application Development",
    term: 6,
    credits: 4,
    format: "studio",
    summary:
      "Kotlin, Compose UI, architecture, state, navigation, data, networking, accessibility, testing, and adaptive layouts.",
    primaryOutcome:
      "Ship a tested, accessible Android application with maintainable architecture and offline-aware data behavior.",
    prerequisiteKeys: ["software-engineering", "human-computer-interaction"],
    competencyKeys: ["software", "human-centered"],
    topics: [
      "Kotlin fundamentals and Android project structure",
      "Compose UI, layouts, and theming",
      "state, events, and lifecycle-aware design",
      "navigation and adaptive interfaces",
      "architecture, view models, and data layers",
      "persistence, networking, and offline behavior",
      "accessibility, testing, and performance",
      "release preparation and a complete Android application",
    ],
    assessmentKinds: ["project", "presentation"],
    concentrationKey: "interactive-applications",
    resource: {
      slug: "android-basics-with-compose",
      title: "Android Basics with Compose",
      provider: "Android Developers",
      url: "https://developer.android.com/courses/android-basics-compose/course",
      kind: "course",
      authors: ["Google Android Developers"],
    },
  },
  {
    key: "applied-cryptography",
    code: "CS636",
    slug: "applied-cryptography",
    title: "Applied Cryptography",
    term: 6,
    credits: 4,
    format: "theory",
    summary:
      "Encryption, authentication, public-key systems, key exchange, signatures, protocol composition, and implementation hazards.",
    primaryOutcome:
      "Select and analyze cryptographic constructions without inventing protocols or overstating security guarantees.",
    prerequisiteKeys: ["computer-security", "discrete-mathematics", "algorithms"],
    competencyKeys: ["security", "mathematics"],
    topics: [
      "security definitions, adversaries, and threat models",
      "one-time pads, stream ciphers, and pseudorandomness",
      "block ciphers and modes of operation",
      "message authentication and authenticated encryption",
      "hash functions and password storage",
      "public-key encryption and number-theoretic foundations",
      "key exchange, digital signatures, and certificates",
      "protocol composition, implementation failures, and a security analysis",
    ],
    assessmentKinds: ["problem set", "oral"],
    concentrationKey: "scalable-secure-systems",
    resource: {
      slug: "stanford-online-cryptography",
      title: "Online Cryptography Course",
      provider: "Stanford University",
      url: "https://crypto.stanford.edu/~dabo/courses/OnlineCrypto/",
      kind: "course",
      authors: ["Dan Boneh"],
    },
  },
] as const satisfies readonly ComputerScienceCourseSpec[];
